<?php

namespace Database\Seeders;

use App\Models\Indikator;
use App\Models\SubItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class SubItemSeeder extends Seeder
{
    /**
     * Seed authentic 515 sub-items parsed from Dasboard QPI Kewilyahan.RW.xlsx.
     */
    public function run(): void
    {
        $indikators = Indikator::pluck('id', 'kode')->toArray();
        $subItems = [];
        $now = now();

        $data = [
            ['ind_kode' => 'A1', 'kode' => 'a', 'teks' => 'Ruang tunggu pelayanan tersedia dan dapat diakses warga tanpa hambatan', 'urutan' => 1],
            ['ind_kode' => 'A1', 'kode' => 'b', 'teks' => 'Ruang tunggu terlihat bersih, bebas sampah dan debu pada saat kunjungan', 'urutan' => 2],
            ['ind_kode' => 'A1', 'kode' => 'c', 'teks' => 'Kursi/tempat duduk tersedia dalam jumlah cukup dan tertata rapi', 'urutan' => 3],
            ['ind_kode' => 'A1', 'kode' => 'd', 'teks' => 'Ruang tunggu memiliki penerangan dan sirkulasi udara yang memadai (kipas angin/AC/ventilasi berfungsi)', 'urutan' => 4],
            ['ind_kode' => 'A1', 'kode' => 'e', 'teks' => 'Tersedia jadwal/petugas piket kebersihan ruang tunggu yang terdokumentasi dan dilaksanakan rutin', 'urutan' => 5],
            ['ind_kode' => 'A2', 'kode' => 'a', 'teks' => 'TPS/Bank Sampah tersedia secara fisik di kelurahan', 'urutan' => 1],
            ['ind_kode' => 'A2', 'kode' => 'b', 'teks' => 'Container/bak sampah dalam kondisi tertutup, bukan terbuka atau tercecer', 'urutan' => 2],
            ['ind_kode' => 'A2', 'kode' => 'c', 'teks' => 'Kapasitas TPS memadai untuk menampung volume sampah harian tanpa meluap', 'urutan' => 3],
            ['ind_kode' => 'A2', 'kode' => 'd', 'teks' => 'Tidak tercium bau menyengat yang mengganggu permukiman di sekitar TPS saat kunjungan', 'urutan' => 4],
            ['ind_kode' => 'A2', 'kode' => 'e', 'teks' => 'TPS memiliki jadwal pengosongan/pembersihan rutin yang terdokumentasi dan dipatuhi', 'urutan' => 5],
            ['ind_kode' => 'A3', 'kode' => 'a', 'teks' => 'Armada truk pengangkut sampah tersedia dan beroperasi di wilayah permukiman', 'urutan' => 1],
            ['ind_kode' => 'A3', 'kode' => 'b', 'teks' => 'Kondisi fisik truk layak jalan, tidak rusak berat/mogok saat beroperasi', 'urutan' => 2],
            ['ind_kode' => 'A3', 'kode' => 'c', 'teks' => 'Bak muatan truk tertutup terpal/penutup selama pengangkutan', 'urutan' => 3],
            ['ind_kode' => 'A3', 'kode' => 'd', 'teks' => 'Tidak ditemukan sampah berceceran di sepanjang rute pengangkutan', 'urutan' => 4],
            ['ind_kode' => 'A3', 'kode' => 'e', 'teks' => 'Armada memiliki catatan perawatan/pemeriksaan berkala yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'A4', 'kode' => 'a', 'teks' => 'Papan informasi jadwal pengangkutan sampah tersedia secara fisik di titik strategis', 'urutan' => 1],
            ['ind_kode' => 'A4', 'kode' => 'b', 'teks' => 'Informasi lokasi TPS tercantum jelas dan dapat dibaca warga', 'urutan' => 2],
            ['ind_kode' => 'A4', 'kode' => 'c', 'teks' => 'Isi informasi pada papan sesuai dengan jadwal aktual yang berlaku, tidak kedaluwarsa', 'urutan' => 3],
            ['ind_kode' => 'A4', 'kode' => 'd', 'teks' => 'Papan informasi terpasang di lebih dari satu titik (RT/RW/kelurahan) yang mudah dijangkau warga', 'urutan' => 4],
            ['ind_kode' => 'A4', 'kode' => 'e', 'teks' => 'Papan informasi diperbarui secara berkala dengan bukti tanggal pemutakhiran', 'urutan' => 5],
            ['ind_kode' => 'A5', 'kode' => 'a', 'teks' => 'Papan/media informasi layanan adminduk tersedia di kantor kecamatan', 'urutan' => 1],
            ['ind_kode' => 'A5', 'kode' => 'b', 'teks' => 'Prosedur permohonan SIBISA tercantum secara lengkap dan mudah dipahami', 'urutan' => 2],
            ['ind_kode' => 'A5', 'kode' => 'c', 'teks' => 'Persyaratan dokumen untuk tiap jenis layanan (KTP-el, KK, akta, KIA) dicantumkan rinci', 'urutan' => 3],
            ['ind_kode' => 'A5', 'kode' => 'd', 'teks' => 'Jadwal layanan jemput bola tercantum dan sesuai dengan pelaksanaan aktual', 'urutan' => 4],
            ['ind_kode' => 'A5', 'kode' => 'e', 'teks' => 'Informasi diperbarui berkala dan tersedia juga dalam bentuk digital (website/medsos/WA) yang sinkron dengan papan fisik', 'urutan' => 5],
            ['ind_kode' => 'B1', 'kode' => 'a', 'teks' => 'Jadwal pengangkutan sampah dari TPS ke TPA telah ditetapkan secara tertulis', 'urutan' => 1],
            ['ind_kode' => 'B1', 'kode' => 'b', 'teks' => 'Armada datang ke TPS sesuai hari yang dijadwalkan dalam 1 minggu terakhir', 'urutan' => 2],
            ['ind_kode' => 'B1', 'kode' => 'c', 'teks' => 'Armada datang sesuai rentang waktu (jam) yang dijadwalkan, bukan hanya harinya', 'urutan' => 3],
            ['ind_kode' => 'B1', 'kode' => 'd', 'teks' => 'Rute pengangkutan diikuti secara konsisten tanpa TPS yang terlewat', 'urutan' => 4],
            ['ind_kode' => 'B1', 'kode' => 'e', 'teks' => 'Tersedia log/catatan pengangkutan (waktu datang-pergi) yang terdokumentasi sebagai bukti kepatuhan jadwal', 'urutan' => 5],
            ['ind_kode' => 'B2', 'kode' => 'a', 'teks' => 'TPS/Bank Sampah buka/dapat diakses warga setiap hari dalam seminggu', 'urutan' => 1],
            ['ind_kode' => 'B2', 'kode' => 'b', 'teks' => 'Tidak ditemukan TPS terkunci/tertutup tanpa pemberitahuan pada jam operasional', 'urutan' => 2],
            ['ind_kode' => 'B2', 'kode' => 'c', 'teks' => 'Petugas/penjaga TPS hadir sesuai jam operasional yang ditetapkan', 'urutan' => 3],
            ['ind_kode' => 'B2', 'kode' => 'd', 'teks' => 'TPS tetap dapat digunakan warga meski di luar jam kerja kantor kecamatan (mis. malam/akhir pekan)', 'urutan' => 4],
            ['ind_kode' => 'B2', 'kode' => 'e', 'teks' => 'Tersedia mekanisme pelaporan bila TPS tidak beroperasi, dan direspons dalam waktu wajar', 'urutan' => 5],
            ['ind_kode' => 'B3', 'kode' => 'a', 'teks' => 'Aplikasi/website SIBISA dapat diakses warga menggunakan perangkat umum (HP/komputer)', 'urutan' => 1],
            ['ind_kode' => 'B3', 'kode' => 'b', 'teks' => 'Warga berhasil melakukan login/registrasi tanpa kendala teknis berulang', 'urutan' => 2],
            ['ind_kode' => 'B3', 'kode' => 'c', 'teks' => 'Proses pengajuan permohonan dapat diselesaikan tanpa error sistem pada saat uji coba', 'urutan' => 3],
            ['ind_kode' => 'B3', 'kode' => 'd', 'teks' => 'Status permohonan dapat dipantau secara real-time oleh pemohon', 'urutan' => 4],
            ['ind_kode' => 'B3', 'kode' => 'e', 'teks' => 'Tersedia catatan uptime/gangguan sistem SIBISA yang menunjukkan tingkat keandalan terukur', 'urutan' => 5],
            ['ind_kode' => 'B4', 'kode' => 'a', 'teks' => 'SOP tertulis mengenai lama waktu penerbitan tiap jenis dokumen tersedia', 'urutan' => 1],
            ['ind_kode' => 'B4', 'kode' => 'b', 'teks' => 'Dokumen yang diuji sampel diterbitkan dalam batas waktu SOP', 'urutan' => 2],
            ['ind_kode' => 'B4', 'kode' => 'c', 'teks' => 'Tidak ditemukan dokumen yang tertunda melebihi batas waktu SOP tanpa alasan tercatat', 'urutan' => 3],
            ['ind_kode' => 'B4', 'kode' => 'd', 'teks' => 'Pemohon menerima notifikasi/informasi bila terjadi keterlambatan', 'urutan' => 4],
            ['ind_kode' => 'B4', 'kode' => 'e', 'teks' => 'Tersedia rekapitulasi/log waktu proses seluruh dokumen yang dapat diverifikasi', 'urutan' => 5],
            ['ind_kode' => 'B5', 'kode' => 'a', 'teks' => 'Jadwal jemput bola adminduk ke kelurahan telah ditetapkan dan diumumkan', 'urutan' => 1],
            ['ind_kode' => 'B5', 'kode' => 'b', 'teks' => 'Layanan jemput bola benar-benar dilaksanakan pada tanggal yang diumumkan (bulan terakhir)', 'urutan' => 2],
            ['ind_kode' => 'B5', 'kode' => 'c', 'teks' => 'Petugas yang hadir sesuai dengan kompetensi, dapat memproses dokumen di lokasi', 'urutan' => 3],
            ['ind_kode' => 'B5', 'kode' => 'd', 'teks' => 'Layanan dilaksanakan di seluruh kelurahan sesuai jadwal, tidak ada kelurahan yang terlewat', 'urutan' => 4],
            ['ind_kode' => 'B5', 'kode' => 'e', 'teks' => 'Tersedia dokumentasi/laporan kehadiran & hasil tiap pelaksanaan jemput bola', 'urutan' => 5],
            ['ind_kode' => 'C1', 'kode' => 'a', 'teks' => 'Tersedia saluran/kontak untuk warga melaporkan TPS penuh/meluap', 'urutan' => 1],
            ['ind_kode' => 'C1', 'kode' => 'b', 'teks' => 'Laporan warga direspons oleh petugas dalam waktu paling lambat 1×24 jam', 'urutan' => 2],
            ['ind_kode' => 'C1', 'kode' => 'c', 'teks' => 'Tindakan lapangan (pengangkutan tambahan/pembersihan) dilakukan setelah laporan diterima', 'urutan' => 3],
            ['ind_kode' => 'C1', 'kode' => 'd', 'teks' => 'Tidak ditemukan kasus TPS meluap yang dibiarkan lebih dari 2 hari tanpa tindak lanjut', 'urutan' => 4],
            ['ind_kode' => 'C1', 'kode' => 'e', 'teks' => 'Tersedia log pengaduan dan tindak lanjut yang terdokumentasi untuk setiap laporan TPS meluap', 'urutan' => 5],
            ['ind_kode' => 'C2', 'kode' => 'a', 'teks' => 'Tersedia saluran resmi bagi warga untuk melaporkan truk yang tidak datang', 'urutan' => 1],
            ['ind_kode' => 'C2', 'kode' => 'b', 'teks' => 'Keluhan diterima dan dicatat oleh petugas yang berwenang', 'urutan' => 2],
            ['ind_kode' => 'C2', 'kode' => 'c', 'teks' => 'Petugas memberikan konfirmasi/tindak lanjut kepada pelapor dalam paling lambat 1×24 jam', 'urutan' => 3],
            ['ind_kode' => 'C2', 'kode' => 'd', 'teks' => 'Armada pengganti/susulan dikirim pada hari yang sama atau keesokan harinya', 'urutan' => 4],
            ['ind_kode' => 'C2', 'kode' => 'e', 'teks' => 'Tersedia rekap keluhan & penyelesaian yang dapat ditelusuri', 'urutan' => 5],
            ['ind_kode' => 'C3', 'kode' => 'a', 'teks' => 'Jadwal gotong royong rutin telah ditetapkan minimal 2 kali per bulan', 'urutan' => 1],
            ['ind_kode' => 'C3', 'kode' => 'b', 'teks' => 'Kegiatan gotong royong benar-benar dilaksanakan sesuai jadwal pada bulan terakhir', 'urutan' => 2],
            ['ind_kode' => 'C3', 'kode' => 'c', 'teks' => 'Aparatur kecamatan/kelurahan turut hadir memobilisasi kegiatan', 'urutan' => 3],
            ['ind_kode' => 'C3', 'kode' => 'd', 'teks' => 'Frekuensi pelaksanaan mencapai atau melebihi target 2x/bulan secara konsisten dalam 3 bulan terakhir', 'urutan' => 4],
            ['ind_kode' => 'C3', 'kode' => 'e', 'teks' => 'Tersedia dokumentasi (foto/absensi/laporan) untuk setiap pelaksanaan gotong royong', 'urutan' => 5],
            ['ind_kode' => 'C4', 'kode' => 'a', 'teks' => 'Warga dapat mengurus dokumen langsung di lokasi jemput bola tanpa harus kembali ke kantor kecamatan', 'urutan' => 1],
            ['ind_kode' => 'C4', 'kode' => 'b', 'teks' => 'Waktu tunggu/antrian warga di lokasi jemput bola tercatat dan dipantau', 'urutan' => 2],
            ['ind_kode' => 'C4', 'kode' => 'c', 'teks' => 'Rata-rata waktu layanan per warga berada dalam batas wajar (mis. maksimal 15 menit) berdasarkan pengamatan', 'urutan' => 3],
            ['ind_kode' => 'C4', 'kode' => 'd', 'teks' => 'Tidak ditemukan antrian yang tidak terlayani hingga sesi jemput bola berakhir', 'urutan' => 4],
            ['ind_kode' => 'C4', 'kode' => 'e', 'teks' => 'Tersedia sistem nomor antrian/pencatatan untuk menjamin kecepatan dan keadilan layanan', 'urutan' => 5],
            ['ind_kode' => 'C5', 'kode' => 'a', 'teks' => 'Tersedia kontak/kanal helpdesk SIBISA yang dapat dihubungi warga (telepon/WA/email)', 'urutan' => 1],
            ['ind_kode' => 'C5', 'kode' => 'b', 'teks' => 'Helpdesk merespons pertanyaan/kendala warga dalam paling lambat 1×24 jam kerja', 'urutan' => 2],
            ['ind_kode' => 'C5', 'kode' => 'c', 'teks' => 'Petugas helpdesk mampu menyelesaikan kendala teknis dasar tanpa eskalasi berlarut', 'urutan' => 3],
            ['ind_kode' => 'C5', 'kode' => 'd', 'teks' => 'Tersedia FAQ/panduan troubleshooting yang mudah diakses warga secara mandiri', 'urutan' => 4],
            ['ind_kode' => 'C5', 'kode' => 'e', 'teks' => 'Tersedia log tiket bantuan & waktu penyelesaian yang terdokumentasi dan dapat dievaluasi', 'urutan' => 5],
            ['ind_kode' => 'D1', 'kode' => 'a', 'teks' => 'Petugas pengelola TPS yang ditugaskan dapat diidentifikasi dengan jelas (nama/SK penugasan)', 'urutan' => 1],
            ['ind_kode' => 'D1', 'kode' => 'b', 'teks' => 'Petugas menggunakan alat pelindung diri dasar (sarung tangan/masker/sepatu bot) saat bertugas', 'urutan' => 2],
            ['ind_kode' => 'D1', 'kode' => 'c', 'teks' => 'Petugas dapat menjelaskan prosedur dasar pemilahan/pengelolaan sampah dengan benar saat ditanya', 'urutan' => 3],
            ['ind_kode' => 'D1', 'kode' => 'd', 'teks' => 'Petugas pernah mengikuti pelatihan/briefing terkait pengelolaan sampah yang aman', 'urutan' => 4],
            ['ind_kode' => 'D1', 'kode' => 'e', 'teks' => 'Tidak ditemukan praktik pengelolaan sampah yang menyalahi prosedur, mis. pembakaran liar, di TPS tersebut', 'urutan' => 5],
            ['ind_kode' => 'D2', 'kode' => 'a', 'teks' => 'Area sekitar TPS tidak tergenang air limbah/lindi yang mencemari tanah', 'urutan' => 1],
            ['ind_kode' => 'D2', 'kode' => 'b', 'teks' => 'Tidak tercium bau menyengat pada radius permukiman terdekat saat kunjungan', 'urutan' => 2],
            ['ind_kode' => 'D2', 'kode' => 'c', 'teks' => 'Tidak ditemukan indikasi vektor penyakit (lalat/tikus dalam jumlah signifikan) di sekitar TPS', 'urutan' => 3],
            ['ind_kode' => 'D2', 'kode' => 'd', 'teks' => 'Sampah dipilah minimal antara organik dan anorganik di lokasi TPS', 'urutan' => 4],
            ['ind_kode' => 'D2', 'kode' => 'e', 'teks' => 'Tersedia jadwal & bukti penyemprotan/desinfeksi atau pengelolaan higienis berkala', 'urutan' => 5],
            ['ind_kode' => 'D3', 'kode' => 'a', 'teks' => 'Sistem SIBISA menggunakan autentikasi (login/OTP) sebelum data pribadi dapat diakses', 'urutan' => 1],
            ['ind_kode' => 'D3', 'kode' => 'b', 'teks' => 'Dokumen fisik warga di loket disimpan di tempat yang tidak dapat diakses sembarang orang', 'urutan' => 2],
            ['ind_kode' => 'D3', 'kode' => 'c', 'teks' => 'Petugas tidak membagikan data pribadi pemohon kepada pihak yang tidak berkepentingan', 'urutan' => 3],
            ['ind_kode' => 'D3', 'kode' => 'd', 'teks' => 'Tersedia kebijakan/SOP tertulis tentang perlindungan data pribadi warga', 'urutan' => 4],
            ['ind_kode' => 'D3', 'kode' => 'e', 'teks' => 'Tidak ditemukan/terlaporkan kasus kebocoran data pribadi warga dalam 1 tahun terakhir', 'urutan' => 5],
            ['ind_kode' => 'D4', 'kode' => 'a', 'teks' => 'Sistem integrasi data dengan RS/sekolah/panti asuhan telah berjalan dan digunakan', 'urutan' => 1],
            ['ind_kode' => 'D4', 'kode' => 'b', 'teks' => 'Dokumen yang diterbitkan melalui integrasi tersebut memiliki kode/verifikasi keabsahan (QR/barcode/nomor validasi)', 'urutan' => 2],
            ['ind_kode' => 'D4', 'kode' => 'c', 'teks' => 'Sampel dokumen hasil integrasi yang diperiksa sesuai dengan data sumber, tidak ada selisih data', 'urutan' => 3],
            ['ind_kode' => 'D4', 'kode' => 'd', 'teks' => 'Warga dapat memverifikasi keabsahan dokumennya secara mandiri, online maupun offline', 'urutan' => 4],
            ['ind_kode' => 'D4', 'kode' => 'e', 'teks' => 'Tidak ditemukan/terlaporkan kasus dokumen tidak sah yang lolos akibat proses integrasi data', 'urutan' => 5],
            ['ind_kode' => 'D5', 'kode' => 'a', 'teks' => 'Petugas mengenakan identitas/seragam yang jelas saat bertugas', 'urutan' => 1],
            ['ind_kode' => 'D5', 'kode' => 'b', 'teks' => 'Petugas menyapa dan melayani warga dengan bahasa yang sopan, diamati langsung atau dilaporkan warga', 'urutan' => 2],
            ['ind_kode' => 'D5', 'kode' => 'c', 'teks' => 'Petugas tidak menunjukkan sikap membeda-bedakan warga berdasarkan status sosial', 'urutan' => 3],
            ['ind_kode' => 'D5', 'kode' => 'd', 'teks' => 'Petugas memberikan penjelasan yang jelas tanpa mempersulit warga saat ditanya', 'urutan' => 4],
            ['ind_kode' => 'D5', 'kode' => 'e', 'teks' => 'Tidak ditemukan/terlaporkan keluhan atas sikap tidak profesional petugas dalam 3 bulan terakhir', 'urutan' => 5],
            ['ind_kode' => 'E1', 'kode' => 'a', 'teks' => 'Kecamatan memiliki penanggung jawab/petugas patroli kebersihan lingkungan sekitar TPS', 'urutan' => 1],
            ['ind_kode' => 'E1', 'kode' => 'b', 'teks' => 'Tidak ditemukan tumpukan sampah liar dalam radius 50 meter dari TPS saat kunjungan', 'urutan' => 2],
            ['ind_kode' => 'E1', 'kode' => 'c', 'teks' => 'Titik-titik rawan sampah liar yang pernah ditemukan telah ditindaklanjuti/dibersihkan', 'urutan' => 3],
            ['ind_kode' => 'E1', 'kode' => 'd', 'teks' => 'Tersedia rambu/papan larangan membuang sampah sembarangan di titik rawan', 'urutan' => 4],
            ['ind_kode' => 'E1', 'kode' => 'e', 'teks' => 'Tersedia laporan/patroli rutin terdokumentasi terkait pemantauan sampah liar', 'urutan' => 5],
            ['ind_kode' => 'E2', 'kode' => 'a', 'teks' => 'Kecamatan/kelurahan mengetahui keberadaan warga lansia/disabilitas yang membutuhkan bantuan pembuangan sampah', 'urutan' => 1],
            ['ind_kode' => 'E2', 'kode' => 'b', 'teks' => 'Tersedia mekanisme/petugas yang membantu pengambilan sampah dari rumah warga lansia/disabilitas', 'urutan' => 2],
            ['ind_kode' => 'E2', 'kode' => 'c', 'teks' => 'Bantuan tersebut benar-benar dilaksanakan secara rutin, bukan insidental', 'urutan' => 3],
            ['ind_kode' => 'E2', 'kode' => 'd', 'teks' => 'Warga lansia/disabilitas yang diwawancarai menyatakan pernah menerima bantuan tersebut', 'urutan' => 4],
            ['ind_kode' => 'E2', 'kode' => 'e', 'teks' => 'Tersedia data/daftar penerima layanan alternatif ini yang terdokumentasi dan diperbarui', 'urutan' => 5],
            ['ind_kode' => 'E3', 'kode' => 'a', 'teks' => 'Tersedia petugas/loket bantuan tatap muka bagi warga yang tidak bisa mengakses SIBISA sendiri', 'urutan' => 1],
            ['ind_kode' => 'E3', 'kode' => 'b', 'teks' => 'Petugas bersedia membantu proses input/pengajuan SIBISA untuk warga yang kesulitan', 'urutan' => 2],
            ['ind_kode' => 'E3', 'kode' => 'c', 'teks' => 'Tersedia jalur layanan manual/offline sebagai alternatif SIBISA bagi warga lanjut usia/gaptek', 'urutan' => 3],
            ['ind_kode' => 'E3', 'kode' => 'd', 'teks' => 'Warga yang diwawancarai menyatakan mendapat bantuan saat mengalami kesulitan mengakses SIBISA', 'urutan' => 4],
            ['ind_kode' => 'E3', 'kode' => 'e', 'teks' => 'Tersedia catatan/log warga yang dibantu secara khusus karena kendala akses digital', 'urutan' => 5],
            ['ind_kode' => 'E4', 'kode' => 'a', 'teks' => 'Pernah dilaksanakan sosialisasi/kampanye tata cara membuang sampah dalam 6 bulan terakhir', 'urutan' => 1],
            ['ind_kode' => 'E4', 'kode' => 'b', 'teks' => 'Materi sosialisasi mencakup jenis sampah, waktu pembuangan, dan larangan yang berlaku', 'urutan' => 2],
            ['ind_kode' => 'E4', 'kode' => 'c', 'teks' => 'Sosialisasi menjangkau lebih dari satu kelurahan/RT dalam wilayah kecamatan', 'urutan' => 3],
            ['ind_kode' => 'E4', 'kode' => 'd', 'teks' => 'Tersedia media sosialisasi permanen (poster/spanduk/konten medsos) yang dapat diakses warga kapan saja', 'urutan' => 4],
            ['ind_kode' => 'E4', 'kode' => 'e', 'teks' => 'Tersedia dokumentasi pelaksanaan (daftar hadir/foto/laporan) untuk tiap sosialisasi yang dilakukan', 'urutan' => 5],
            ['ind_kode' => 'E5', 'kode' => 'a', 'teks' => 'Tersedia lebih dari satu kanal pengaduan (langsung, telepon/WA, online) yang diketahui warga', 'urutan' => 1],
            ['ind_kode' => 'E5', 'kode' => 'b', 'teks' => 'Kanal pengaduan tersebut aktif digunakan dan dapat diakses tanpa biaya', 'urutan' => 2],
            ['ind_kode' => 'E5', 'kode' => 'c', 'teks' => 'Warga yang mencoba menyampaikan keluhan mendapat tanggapan awal dalam waktu wajar', 'urutan' => 3],
            ['ind_kode' => 'E5', 'kode' => 'd', 'teks' => 'Warga tidak diminta prosedur berbelit (surat resmi/berjenjang) hanya untuk menyampaikan keluhan sederhana', 'urutan' => 4],
            ['ind_kode' => 'E5', 'kode' => 'e', 'teks' => 'Tersedia rekap aspirasi/keluhan warga beserta status tindak lanjutnya yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'B1', 'kode' => 'a', 'teks' => 'TPS/Bank Sampah tersedia secara fisik di setiap kelurahan tanpa terkecuali', 'urutan' => 1],
            ['ind_kode' => 'B1', 'kode' => 'b', 'teks' => 'Setiap TPS memiliki petugas/penjaga yang ditetapkan dengan SK/penugasan resmi', 'urutan' => 2],
            ['ind_kode' => 'B1', 'kode' => 'c', 'teks' => 'Jadwal operasional TPS ditetapkan tertulis dan dipasang di lokasi', 'urutan' => 3],
            ['ind_kode' => 'B1', 'kode' => 'd', 'teks' => 'Kapasitas TPS memadai untuk volume sampah kelurahan tanpa meluap dalam kondisi normal', 'urutan' => 4],
            ['ind_kode' => 'B1', 'kode' => 'e', 'teks' => 'Tersedia laporan operasional TPS per kelurahan yang direkap kecamatan secara berkala', 'urutan' => 5],
            ['ind_kode' => 'B2', 'kode' => 'a', 'teks' => 'Kecamatan memiliki mekanisme koordinasi rutin dengan pihak pengangkut sampah ke TPA', 'urutan' => 1],
            ['ind_kode' => 'B2', 'kode' => 'b', 'teks' => 'Jadwal pengangkutan disepakati tertulis antara kecamatan dan pihak pengangkut', 'urutan' => 2],
            ['ind_kode' => 'B2', 'kode' => 'c', 'teks' => 'Tidak ditemukan akumulasi sampah lebih dari 2 hari di TPS manapun pada bulan terakhir', 'urutan' => 3],
            ['ind_kode' => 'B2', 'kode' => 'd', 'teks' => 'Kecamatan melakukan pemantauan lapangan berkala terhadap kondisi TPS', 'urutan' => 4],
            ['ind_kode' => 'B2', 'kode' => 'e', 'teks' => 'Tersedia laporan koordinasi & tindak lanjut bila terjadi keterlambatan pengangkutan', 'urutan' => 5],
            ['ind_kode' => 'B3', 'kode' => 'a', 'teks' => 'Program gotong royong rutin tercantum dalam rencana kerja kecamatan/kelurahan', 'urutan' => 1],
            ['ind_kode' => 'B3', 'kode' => 'b', 'teks' => 'Pelaksanaan gotong royong tercatat minimal 2 kali dalam bulan terakhir', 'urutan' => 2],
            ['ind_kode' => 'B3', 'kode' => 'c', 'teks' => 'Frekuensi minimal 2x/bulan tersebut konsisten selama 3 bulan terakhir', 'urutan' => 3],
            ['ind_kode' => 'B3', 'kode' => 'd', 'teks' => 'Kegiatan melibatkan lebih dari satu kelurahan dalam wilayah kecamatan', 'urutan' => 4],
            ['ind_kode' => 'B3', 'kode' => 'e', 'teks' => 'Tersedia laporan/dokumentasi pelaksanaan setiap kegiatan gotong royong yang terarsip rapi', 'urutan' => 5],
            ['ind_kode' => 'B4', 'kode' => 'a', 'teks' => 'Kecamatan memiliki data/peta wilayah permukiman yang menjadi cakupan layanan pengangkutan sampah', 'urutan' => 1],
            ['ind_kode' => 'B4', 'kode' => 'b', 'teks' => 'Data persentase permukiman yang terlayani telah dihitung dan didokumentasikan', 'urutan' => 2],
            ['ind_kode' => 'B4', 'kode' => 'c', 'teks' => 'Persentase permukiman terlayani mencapai target minimal yang ditetapkan kebijakan kota', 'urutan' => 3],
            ['ind_kode' => 'B4', 'kode' => 'd', 'teks' => 'Kecamatan memiliki rencana tindak lanjut untuk wilayah yang belum terlayani', 'urutan' => 4],
            ['ind_kode' => 'B4', 'kode' => 'e', 'teks' => 'Data cakupan layanan diperbarui secara berkala, bukan data lama/statis', 'urutan' => 5],
            ['ind_kode' => 'B5', 'kode' => 'a', 'teks' => 'Kecamatan memiliki program kampanye edukasi persampahan yang terjadwal', 'urutan' => 1],
            ['ind_kode' => 'B5', 'kode' => 'b', 'teks' => 'Kampanye edukasi terlaksana minimal 1 kali pada bulan terakhir', 'urutan' => 2],
            ['ind_kode' => 'B5', 'kode' => 'c', 'teks' => 'Frekuensi minimal 1x/bulan tersebut konsisten selama 3 bulan terakhir', 'urutan' => 3],
            ['ind_kode' => 'B5', 'kode' => 'd', 'teks' => 'Kampanye menjangkau lebih dari satu segmen warga (RT/RW/sekolah/komunitas)', 'urutan' => 4],
            ['ind_kode' => 'B5', 'kode' => 'e', 'teks' => 'Tersedia dokumentasi/laporan hasil setiap kampanye edukasi yang dilaksanakan', 'urutan' => 5],
            ['ind_kode' => 'B6', 'kode' => 'a', 'teks' => 'Kecamatan memiliki materi promosi (banner/pamflet/konten) tentang penggunaan SIBISA', 'urutan' => 1],
            ['ind_kode' => 'B6', 'kode' => 'b', 'teks' => 'Aparatur pernah memberikan bimbingan langsung/pelatihan singkat kepada warga tentang SIBISA', 'urutan' => 2],
            ['ind_kode' => 'B6', 'kode' => 'c', 'teks' => 'Promosi SIBISA dilakukan melalui lebih dari satu kanal (tatap muka, medsos, RT/RW)', 'urutan' => 3],
            ['ind_kode' => 'B6', 'kode' => 'd', 'teks' => 'Terdapat peningkatan/data jumlah pengguna SIBISA yang tercatat dari waktu ke waktu', 'urutan' => 4],
            ['ind_kode' => 'B6', 'kode' => 'e', 'teks' => 'Tersedia laporan kegiatan promosi & bimbingan SIBISA yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'B7', 'kode' => 'a', 'teks' => 'Jadwal jemput bola adminduk ke kelurahan ditetapkan tertulis', 'urutan' => 1],
            ['ind_kode' => 'B7', 'kode' => 'b', 'teks' => 'Pelaksanaan jemput bola tercatat minimal 2 kali pada bulan terakhir', 'urutan' => 2],
            ['ind_kode' => 'B7', 'kode' => 'c', 'teks' => 'Frekuensi tersebut konsisten selama 3 bulan terakhir', 'urutan' => 3],
            ['ind_kode' => 'B7', 'kode' => 'd', 'teks' => 'Data jumlah dokumen yang diterbitkan pada setiap sesi jemput bola tercatat', 'urutan' => 4],
            ['ind_kode' => 'B7', 'kode' => 'e', 'teks' => 'Laporan jemput bola (jadwal, lokasi, hasil) terdokumentasi dan dapat diverifikasi', 'urutan' => 5],
            ['ind_kode' => 'B8', 'kode' => 'a', 'teks' => 'Kecamatan memiliki daftar RS/klinik di wilayahnya yang menjadi target integrasi data', 'urutan' => 1],
            ['ind_kode' => 'B8', 'kode' => 'b', 'teks' => 'Kesepakatan/nota kerja sama integrasi data dengan minimal satu RS/klinik telah ditandatangani', 'urutan' => 2],
            ['ind_kode' => 'B8', 'kode' => 'c', 'teks' => 'Sistem integrasi data dengan RS/klinik tersebut telah berjalan secara teknis, bukan sebatas MoU', 'urutan' => 3],
            ['ind_kode' => 'B8', 'kode' => 'd', 'teks' => 'Integrasi mencakup lebih dari satu RS/klinik di wilayah kecamatan', 'urutan' => 4],
            ['ind_kode' => 'B8', 'kode' => 'e', 'teks' => 'Tersedia laporan/data hasil pemanfaatan integrasi, mis. jumlah warga yang terbantu, secara berkala', 'urutan' => 5],
            ['ind_kode' => 'B9', 'kode' => 'a', 'teks' => 'Kecamatan memiliki daftar sekolah & panti asuhan di wilayahnya yang menjadi target integrasi data', 'urutan' => 1],
            ['ind_kode' => 'B9', 'kode' => 'b', 'teks' => 'Kesepakatan/nota kerja sama integrasi data dengan minimal satu sekolah/panti asuhan telah ada', 'urutan' => 2],
            ['ind_kode' => 'B9', 'kode' => 'c', 'teks' => 'Sistem integrasi data tersebut telah berjalan secara teknis', 'urutan' => 3],
            ['ind_kode' => 'B9', 'kode' => 'd', 'teks' => 'Integrasi mencakup lebih dari satu sekolah/panti asuhan di wilayah kecamatan', 'urutan' => 4],
            ['ind_kode' => 'B9', 'kode' => 'e', 'teks' => 'Tersedia laporan/data hasil pemanfaatan integrasi yang diperbarui berkala', 'urutan' => 5],
            ['ind_kode' => 'B10', 'kode' => 'a', 'teks' => 'Kecamatan mencatat jumlah total permohonan adminduk yang masuk (SIBISA & loket manual)', 'urutan' => 1],
            ['ind_kode' => 'B10', 'kode' => 'b', 'teks' => 'Kecamatan mencatat jumlah permohonan yang selesai tepat waktu sesuai SOP', 'urutan' => 2],
            ['ind_kode' => 'B10', 'kode' => 'c', 'teks' => 'Persentase penyelesaian tepat waktu mencapai target minimal yang ditetapkan', 'urutan' => 3],
            ['ind_kode' => 'B10', 'kode' => 'd', 'teks' => 'Permohonan yang terlambat memiliki catatan alasan & tindak lanjut', 'urutan' => 4],
            ['ind_kode' => 'B10', 'kode' => 'e', 'teks' => 'Data rekapitulasi ketepatan waktu ini dilaporkan secara berkala ke tingkat kota', 'urutan' => 5],
            ['ind_kode' => 'B11', 'kode' => 'a', 'teks' => 'Tersedia daftar aparatur/petugas yang bertanggung jawab atas pengelolaan TPS', 'urutan' => 1],
            ['ind_kode' => 'B11', 'kode' => 'b', 'teks' => 'Minimal satu petugas per kelurahan pernah mengikuti pelatihan pengelolaan TPS', 'urutan' => 2],
            ['ind_kode' => 'B11', 'kode' => 'c', 'teks' => 'Materi pelatihan mencakup SOP operasional dan K3 persampahan dasar', 'urutan' => 3],
            ['ind_kode' => 'B11', 'kode' => 'd', 'teks' => 'Pelatihan diikuti dalam 1 tahun terakhir, bukan pelatihan lama yang sudah kedaluwarsa', 'urutan' => 4],
            ['ind_kode' => 'B11', 'kode' => 'e', 'teks' => 'Tersedia sertifikat/bukti keikutsertaan pelatihan yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'B12', 'kode' => 'a', 'teks' => 'Tersedia daftar aparatur yang bertugas mengoperasikan SIBISA', 'urutan' => 1],
            ['ind_kode' => 'B12', 'kode' => 'b', 'teks' => 'Minimal satu petugas per kecamatan pernah mengikuti pelatihan SIBISA', 'urutan' => 2],
            ['ind_kode' => 'B12', 'kode' => 'c', 'teks' => 'Petugas mampu mendemonstrasikan pengoperasian dasar SIBISA saat diminta', 'urutan' => 3],
            ['ind_kode' => 'B12', 'kode' => 'd', 'teks' => 'Pelatihan diikuti dalam 1 tahun terakhir', 'urutan' => 4],
            ['ind_kode' => 'B12', 'kode' => 'e', 'teks' => 'Tersedia sertifikat/bukti keikutsertaan pelatihan yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'B13', 'kode' => 'a', 'teks' => 'Kecamatan memiliki akun e-office/WA resmi/media sosial yang aktif', 'urutan' => 1],
            ['ind_kode' => 'B13', 'kode' => 'b', 'teks' => 'Akun tersebut digunakan untuk komunikasi operasional dalam 1 bulan terakhir', 'urutan' => 2],
            ['ind_kode' => 'B13', 'kode' => 'c', 'teks' => 'Informasi yang dibagikan relevan dengan layanan publik, bukan hanya seremonial', 'urutan' => 3],
            ['ind_kode' => 'B13', 'kode' => 'd', 'teks' => 'Warga terlihat/tercatat berinteraksi (komentar/respons) pada kanal tersebut', 'urutan' => 4],
            ['ind_kode' => 'B13', 'kode' => 'e', 'teks' => 'Tersedia pengelola/admin resmi yang ditugaskan mengelola kanal tersebut secara rutin', 'urutan' => 5],
            ['ind_kode' => 'B14', 'kode' => 'a', 'teks' => 'Kecamatan memiliki dokumen pagu anggaran persampahan & adminduk tahun berjalan', 'urutan' => 1],
            ['ind_kode' => 'B14', 'kode' => 'b', 'teks' => 'Kecamatan mencatat realisasi anggaran secara berkala (bulanan/triwulanan)', 'urutan' => 2],
            ['ind_kode' => 'B14', 'kode' => 'c', 'teks' => 'Realisasi anggaran berjalan sesuai atau mendekati target periode berjalan, tidak jauh menyimpang', 'urutan' => 3],
            ['ind_kode' => 'B14', 'kode' => 'd', 'teks' => 'Tidak ditemukan penyerapan anggaran yang menumpuk di akhir tahun sebagai indikasi perencanaan buruk', 'urutan' => 4],
            ['ind_kode' => 'B14', 'kode' => 'e', 'teks' => 'Tersedia laporan realisasi anggaran yang dapat diverifikasi dan diaudit', 'urutan' => 5],
            ['ind_kode' => 'B15', 'kode' => 'a', 'teks' => 'Kecamatan memiliki data biaya operasional persampahan dan jumlah sampah terangkut dalam ton', 'urutan' => 1],
            ['ind_kode' => 'B15', 'kode' => 'b', 'teks' => 'Kecamatan memiliki data biaya operasional adminduk dan jumlah dokumen diterbitkan', 'urutan' => 2],
            ['ind_kode' => 'B15', 'kode' => 'c', 'teks' => 'Rasio biaya per ton sampah dan per dokumen telah dihitung secara berkala', 'urutan' => 3],
            ['ind_kode' => 'B15', 'kode' => 'd', 'teks' => 'Rasio tersebut berada dalam batas wajar/efisien dibanding standar atau rata-rata kota', 'urutan' => 4],
            ['ind_kode' => 'B15', 'kode' => 'e', 'teks' => 'Tersedia laporan analisis efisiensi biaya yang digunakan sebagai dasar perbaikan', 'urutan' => 5],
            ['ind_kode' => 'C1', 'kode' => 'a', 'teks' => 'Jadwal pengangkutan sampah tersedia dalam bentuk tertulis/dokumen resmi', 'urutan' => 1],
            ['ind_kode' => 'C1', 'kode' => 'b', 'teks' => 'Jadwal tersebut dipasang di papan pengumuman fisik yang dapat dilihat warga', 'urutan' => 2],
            ['ind_kode' => 'C1', 'kode' => 'c', 'teks' => 'Jadwal juga disebarkan melalui grup WA RT/RW atau media sosial kelurahan', 'urutan' => 3],
            ['ind_kode' => 'C1', 'kode' => 'd', 'teks' => 'Informasi yang diumumkan sesuai dengan pelaksanaan aktual, tidak menyesatkan', 'urutan' => 4],
            ['ind_kode' => 'C1', 'kode' => 'e', 'teks' => 'Pembaruan jadwal, bila ada perubahan, diumumkan ulang melalui kanal yang sama', 'urutan' => 5],
            ['ind_kode' => 'C2', 'kode' => 'a', 'teks' => 'Informasi lokasi TPS/Bank Sampah dapat diperoleh warga dengan mudah', 'urutan' => 1],
            ['ind_kode' => 'C2', 'kode' => 'b', 'teks' => 'Informasi kapasitas & jam operasional TPS dipublikasikan', 'urutan' => 2],
            ['ind_kode' => 'C2', 'kode' => 'c', 'teks' => 'Tata tertib penggunaan TPS (jenis sampah, jam buang) dipasang di lokasi', 'urutan' => 3],
            ['ind_kode' => 'C2', 'kode' => 'd', 'teks' => 'Informasi tersedia dalam lebih dari satu bentuk, baik papan fisik maupun digital', 'urutan' => 4],
            ['ind_kode' => 'C2', 'kode' => 'e', 'teks' => 'Informasi diperbarui bila terjadi perubahan kebijakan/operasional TPS', 'urutan' => 5],
            ['ind_kode' => 'C3', 'kode' => 'a', 'teks' => 'Prosedur pengajuan SIBISA dipublikasikan secara tertulis', 'urutan' => 1],
            ['ind_kode' => 'C3', 'kode' => 'b', 'teks' => 'Persyaratan dokumen untuk tiap jenis layanan dicantumkan lengkap', 'urutan' => 2],
            ['ind_kode' => 'C3', 'kode' => 'c', 'teks' => 'Informasi biaya, termasuk pernyataan gratis bila berlaku, dinyatakan eksplisit', 'urutan' => 3],
            ['ind_kode' => 'C3', 'kode' => 'd', 'teks' => 'Publikasi tersedia di lebih dari satu kanal (website/papan/medsos kecamatan)', 'urutan' => 4],
            ['ind_kode' => 'C3', 'kode' => 'e', 'teks' => 'Informasi tersebut sesuai dengan praktik pelayanan aktual saat diverifikasi, tidak ada pungutan tidak resmi', 'urutan' => 5],
            ['ind_kode' => 'C4', 'kode' => 'a', 'teks' => 'Jadwal jemput bola diumumkan minimal 3 hari sebelum pelaksanaan', 'urutan' => 1],
            ['ind_kode' => 'C4', 'kode' => 'b', 'teks' => 'Pengumuman mencantumkan kelurahan, tanggal, waktu, dan jenis dokumen yang dilayani', 'urutan' => 2],
            ['ind_kode' => 'C4', 'kode' => 'c', 'teks' => 'Pengumuman disebarkan melalui kanal yang menjangkau warga kelurahan sasaran (RT/RW/WA/papan)', 'urutan' => 3],
            ['ind_kode' => 'C4', 'kode' => 'd', 'teks' => 'Realisasi pelaksanaan sesuai dengan yang diumumkan, tidak berubah mendadak tanpa notifikasi', 'urutan' => 4],
            ['ind_kode' => 'C4', 'kode' => 'e', 'teks' => 'Tersedia bukti/arsip pengumuman untuk setiap sesi jemput bola yang dilaksanakan', 'urutan' => 5],
            ['ind_kode' => 'C5', 'kode' => 'a', 'teks' => 'Kecamatan menyusun laporan evaluasi TPS secara berkala (bulanan/triwulanan)', 'urutan' => 1],
            ['ind_kode' => 'C5', 'kode' => 'b', 'teks' => 'Laporan mencakup data kondisi fisik dan operasional tiap TPS', 'urutan' => 2],
            ['ind_kode' => 'C5', 'kode' => 'c', 'teks' => 'Laporan mencakup capaian program pengangkutan: volume, frekuensi, dan kendala', 'urutan' => 3],
            ['ind_kode' => 'C5', 'kode' => 'd', 'teks' => 'Laporan tersebut dapat diakses/diminta oleh publik atau warga yang berkepentingan', 'urutan' => 4],
            ['ind_kode' => 'C5', 'kode' => 'e', 'teks' => 'Laporan digunakan sebagai dasar tindak lanjut/perbaikan yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'C6', 'kode' => 'a', 'teks' => 'Kanal pengaduan resmi terkait TPS meluap/armada tidak datang tersedia dan diketahui warga', 'urutan' => 1],
            ['ind_kode' => 'C6', 'kode' => 'b', 'teks' => 'Prosedur pengaduan (cara melapor, ke siapa) diinformasikan secara terbuka', 'urutan' => 2],
            ['ind_kode' => 'C6', 'kode' => 'c', 'teks' => 'Pengaduan yang masuk dicatat dalam suatu sistem/buku register', 'urutan' => 3],
            ['ind_kode' => 'C6', 'kode' => 'd', 'teks' => 'Setiap pengaduan memiliki status tindak lanjut yang dapat dipantau', 'urutan' => 4],
            ['ind_kode' => 'C6', 'kode' => 'e', 'teks' => 'Terdapat bukti penyelesaian nyata, bukan sekadar tercatat, untuk pengaduan yang masuk', 'urutan' => 5],
            ['ind_kode' => 'C7', 'kode' => 'a', 'teks' => 'Kecamatan menyusun laporan pertanggungjawaban (LPJ) layanan adminduk secara berkala', 'urutan' => 1],
            ['ind_kode' => 'C7', 'kode' => 'b', 'teks' => 'LPJ mencakup capaian SIBISA, jemput bola, dan loket manual', 'urutan' => 2],
            ['ind_kode' => 'C7', 'kode' => 'c', 'teks' => 'LPJ disampaikan kepada atasan/instansi terkait sesuai jadwal yang ditetapkan', 'urutan' => 3],
            ['ind_kode' => 'C7', 'kode' => 'd', 'teks' => 'Ringkasan LPJ juga dikomunikasikan kepada masyarakat, tidak hanya internal', 'urutan' => 4],
            ['ind_kode' => 'C7', 'kode' => 'e', 'teks' => 'LPJ periode-periode sebelumnya terarsip dan dapat ditelusuri', 'urutan' => 5],
            ['ind_kode' => 'C8', 'kode' => 'a', 'teks' => 'Kecamatan memiliki daftar komunitas mitra (PKK, Karang Taruna, RT/RW, tokoh masyarakat)', 'urutan' => 1],
            ['ind_kode' => 'C8', 'kode' => 'b', 'teks' => 'Komunitas tersebut dilibatkan/diundang dalam kegiatan gotong royong', 'urutan' => 2],
            ['ind_kode' => 'C8', 'kode' => 'c', 'teks' => 'Komunitas diberi peran dalam pengawasan kebersihan TPS, bukan hanya penonton', 'urutan' => 3],
            ['ind_kode' => 'C8', 'kode' => 'd', 'teks' => 'Keterlibatan tersebut terjadi secara rutin/berulang, bukan satu kali insidental', 'urutan' => 4],
            ['ind_kode' => 'C8', 'kode' => 'e', 'teks' => 'Tersedia dokumentasi keterlibatan komunitas (daftar hadir/laporan kegiatan bersama)', 'urutan' => 5],
            ['ind_kode' => 'C9', 'kode' => 'a', 'teks' => 'Kecamatan/kelurahan menyelenggarakan forum musrenbang/rembug kelurahan secara rutin', 'urutan' => 1],
            ['ind_kode' => 'C9', 'kode' => 'b', 'teks' => 'Isu persampahan (kondisi TPS, rute, armada) masuk dalam agenda forum tersebut', 'urutan' => 2],
            ['ind_kode' => 'C9', 'kode' => 'c', 'teks' => 'Usulan warga terkait persampahan dari forum tercatat dalam risalah/notulen', 'urutan' => 3],
            ['ind_kode' => 'C9', 'kode' => 'd', 'teks' => 'Terdapat tindak lanjut nyata atas usulan warga terkait persampahan dari forum sebelumnya', 'urutan' => 4],
            ['ind_kode' => 'C9', 'kode' => 'e', 'teks' => 'Notulen/dokumentasi forum yang membahas isu persampahan terarsip dan dapat diverifikasi', 'urutan' => 5],
            ['ind_kode' => 'C10', 'kode' => 'a', 'teks' => 'Kecamatan pernah meminta masukan warga terkait pelaksanaan SIBISA/jemput bola', 'urutan' => 1],
            ['ind_kode' => 'C10', 'kode' => 'b', 'teks' => 'Masukan warga tersebut dikumpulkan melalui mekanisme yang jelas (survei/forum/kotak saran)', 'urutan' => 2],
            ['ind_kode' => 'C10', 'kode' => 'c', 'teks' => 'Masukan warga didokumentasikan dan dianalisis oleh kecamatan', 'urutan' => 3],
            ['ind_kode' => 'C10', 'kode' => 'd', 'teks' => 'Terdapat perubahan/perbaikan layanan adminduk yang merupakan hasil masukan warga', 'urutan' => 4],
            ['ind_kode' => 'C10', 'kode' => 'e', 'teks' => 'Warga mengetahui/menyadari bahwa masukan mereka ditindaklanjuti, dikonfirmasi via wawancara', 'urutan' => 5],
            ['ind_kode' => 'C11', 'kode' => 'a', 'teks' => 'Kecamatan/kelurahan mengetahui dan memiliki salinan Perda/Perwali kebersihan yang berlaku', 'urutan' => 1],
            ['ind_kode' => 'C11', 'kode' => 'b', 'teks' => 'SOP teknis pengelolaan TPS tersedia secara tertulis di tingkat kecamatan/kelurahan', 'urutan' => 2],
            ['ind_kode' => 'C11', 'kode' => 'c', 'teks' => 'Praktik pengelolaan TPS di lapangan sesuai dengan SOP yang ditetapkan, diverifikasi saat kunjungan', 'urutan' => 3],
            ['ind_kode' => 'C11', 'kode' => 'd', 'teks' => 'Tidak ditemukan pelanggaran standar kesehatan lingkungan yang signifikan di TPS', 'urutan' => 4],
            ['ind_kode' => 'C11', 'kode' => 'e', 'teks' => 'Tersedia bukti pembinaan/pengawasan kepatuhan terhadap Perda/Perwali yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'C12', 'kode' => 'a', 'teks' => 'Petugas mengetahui dan memiliki acuan ketentuan/regulasi Disdukcapil yang berlaku', 'urutan' => 1],
            ['ind_kode' => 'C12', 'kode' => 'b', 'teks' => 'Prosedur penerbitan dokumen di lapangan sesuai dengan ketentuan tersebut', 'urutan' => 2],
            ['ind_kode' => 'C12', 'kode' => 'c', 'teks' => 'Tidak ditemukan penyimpangan prosedur, seperti pungutan liar atau pemalsuan, dalam sampel dokumen yang diperiksa', 'urutan' => 3],
            ['ind_kode' => 'C12', 'kode' => 'd', 'teks' => 'Petugas mengikuti pembaruan regulasi/ketentuan terbaru dari Disdukcapil, ada bukti sosialisasi internal', 'urutan' => 4],
            ['ind_kode' => 'C12', 'kode' => 'e', 'teks' => 'Tersedia mekanisme pengawasan/audit kepatuhan regulasi yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'D1', 'kode' => 'a', 'teks' => 'SIBISA digunakan untuk minimal satu jenis layanan adminduk', 'urutan' => 1],
            ['ind_kode' => 'D1', 'kode' => 'b', 'teks' => 'SIBISA digunakan untuk lebih dari satu jenis layanan, misalnya KTP-el dan KK', 'urutan' => 2],
            ['ind_kode' => 'D1', 'kode' => 'c', 'teks' => 'SIBISA digunakan untuk seluruh 4 jenis layanan: KTP-el, KK, Akta Kelahiran, dan KIA', 'urutan' => 3],
            ['ind_kode' => 'D1', 'kode' => 'd', 'teks' => 'Penggunaan SIBISA untuk seluruh layanan tersebut konsisten dalam 3 bulan terakhir, bukan uji coba sesaat', 'urutan' => 4],
            ['ind_kode' => 'D1', 'kode' => 'e', 'teks' => 'Tersedia data statistik penggunaan SIBISA per jenis layanan yang menunjukkan pemanfaatan aktif dan menyeluruh', 'urutan' => 5],
            ['ind_kode' => 'D2', 'kode' => 'a', 'teks' => 'Kecamatan memiliki minimal satu kanal digital resmi (website/medsos/WA Official)', 'urutan' => 1],
            ['ind_kode' => 'D2', 'kode' => 'b', 'teks' => 'Kanal tersebut digunakan untuk menyampaikan notifikasi jadwal jemput bola', 'urutan' => 2],
            ['ind_kode' => 'D2', 'kode' => 'c', 'teks' => 'Kanal tersebut juga digunakan untuk info status permohonan dokumen', 'urutan' => 3],
            ['ind_kode' => 'D2', 'kode' => 'd', 'teks' => 'Kanal aktif memposting/merespons dalam 1 bulan terakhir, bukan kanal mati', 'urutan' => 4],
            ['ind_kode' => 'D2', 'kode' => 'e', 'teks' => 'Warga terkonfirmasi memanfaatkan kanal tersebut untuk memperoleh informasi, via wawancara/data interaksi', 'urutan' => 5],
            ['ind_kode' => 'D3', 'kode' => 'a', 'teks' => 'Kerja sama/integrasi teknis dengan minimal satu RS/klinik/puskesmas telah disepakati', 'urutan' => 1],
            ['ind_kode' => 'D3', 'kode' => 'b', 'teks' => 'Sistem integrasi tersebut telah diuji dan berfungsi secara teknis', 'urutan' => 2],
            ['ind_kode' => 'D3', 'kode' => 'c', 'teks' => 'Warga benar-benar dapat mengurus dokumen kependudukan bersamaan kunjungan layanan kesehatan', 'urutan' => 3],
            ['ind_kode' => 'D3', 'kode' => 'd', 'teks' => 'Integrasi mencakup lebih dari satu fasilitas kesehatan di wilayah kecamatan', 'urutan' => 4],
            ['ind_kode' => 'D3', 'kode' => 'e', 'teks' => 'Tersedia data jumlah warga yang terlayani melalui skema integrasi ini secara berkala', 'urutan' => 5],
            ['ind_kode' => 'D4', 'kode' => 'a', 'teks' => 'Kerja sama integrasi dengan minimal satu sekolah/panti asuhan telah disepakati', 'urutan' => 1],
            ['ind_kode' => 'D4', 'kode' => 'b', 'teks' => 'Sistem integrasi tersebut telah diuji dan berfungsi secara teknis', 'urutan' => 2],
            ['ind_kode' => 'D4', 'kode' => 'c', 'teks' => 'Data yang terintegrasi tersimpan dalam sistem yang terverifikasi, bukan pencatatan manual lepas', 'urutan' => 3],
            ['ind_kode' => 'D4', 'kode' => 'd', 'teks' => 'Integrasi mencakup lebih dari satu sekolah/panti asuhan di wilayah kecamatan', 'urutan' => 4],
            ['ind_kode' => 'D4', 'kode' => 'e', 'teks' => 'Tersedia laporan pemanfaatan integrasi ini yang diperbarui secara berkala', 'urutan' => 5],
            ['ind_kode' => 'D5', 'kode' => 'a', 'teks' => 'Sistem/aplikasi pemantauan status TPS tersedia, meski sederhana seperti laporan via WA terstruktur', 'urutan' => 1],
            ['ind_kode' => 'D5', 'kode' => 'b', 'teks' => 'Data status TPS diperbarui minimal harian', 'urutan' => 2],
            ['ind_kode' => 'D5', 'kode' => 'c', 'teks' => 'Petugas dapat mengakses data tersebut untuk menjadwalkan pengangkutan secara responsif', 'urutan' => 3],
            ['ind_kode' => 'D5', 'kode' => 'd', 'teks' => 'Sistem mencakup seluruh TPS di wilayah kecamatan, bukan sebagian', 'urutan' => 4],
            ['ind_kode' => 'D5', 'kode' => 'e', 'teks' => 'Tersedia riwayat data (histori) status TPS yang dapat dianalisis untuk perbaikan layanan', 'urutan' => 5],
            ['ind_kode' => 'D6', 'kode' => 'a', 'teks' => 'Armada pengangkut sampah dilengkapi perangkat GPS/pelacak', 'urutan' => 1],
            ['ind_kode' => 'D6', 'kode' => 'b', 'teks' => 'Data posisi/rute armada dapat dipantau secara digital oleh kecamatan/operator', 'urutan' => 2],
            ['ind_kode' => 'D6', 'kode' => 'c', 'teks' => 'Data tracking digunakan untuk mengevaluasi/menyesuaikan rute secara berkala', 'urutan' => 3],
            ['ind_kode' => 'D6', 'kode' => 'd', 'teks' => 'Sistem mencakup seluruh armada yang beroperasi di kecamatan', 'urutan' => 4],
            ['ind_kode' => 'D6', 'kode' => 'e', 'teks' => 'Tersedia laporan optimasi rute berbasis data digital yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'D7', 'kode' => 'a', 'teks' => 'Grup WA RT/RW atau konten media sosial kelurahan terkait persampahan tersedia', 'urutan' => 1],
            ['ind_kode' => 'D7', 'kode' => 'b', 'teks' => 'Media tersebut memuat info jadwal TPS dan jadwal pengangkutan', 'urutan' => 2],
            ['ind_kode' => 'D7', 'kode' => 'c', 'teks' => 'Media tersebut juga memuat info kegiatan Gerakan Peduli Lingkungan', 'urutan' => 3],
            ['ind_kode' => 'D7', 'kode' => 'd', 'teks' => 'Media aktif memposting pembaruan dalam 1 bulan terakhir', 'urutan' => 4],
            ['ind_kode' => 'D7', 'kode' => 'e', 'teks' => 'Warga terkonfirmasi menjadi anggota/mengikuti media tersebut dalam jumlah signifikan', 'urutan' => 5],
            ['ind_kode' => 'D8', 'kode' => 'a', 'teks' => 'Kecamatan memiliki koneksi internet yang berfungsi di lokasi layanan', 'urutan' => 1],
            ['ind_kode' => 'D8', 'kode' => 'b', 'teks' => 'Kecepatan/koneksi internet memadai untuk mengakses SIBISA tanpa gangguan berarti', 'urutan' => 2],
            ['ind_kode' => 'D8', 'kode' => 'c', 'teks' => 'Perangkat komputer/tablet operasional tersedia dan berfungsi baik untuk layanan digital', 'urutan' => 3],
            ['ind_kode' => 'D8', 'kode' => 'd', 'teks' => 'Jumlah perangkat mencukupi kebutuhan operasional, tidak menyebabkan antrean akibat keterbatasan alat', 'urutan' => 4],
            ['ind_kode' => 'D8', 'kode' => 'e', 'teks' => 'Tersedia rencana/anggaran pemeliharaan perangkat & konektivitas secara berkala', 'urutan' => 5],
            ['ind_kode' => 'D9', 'kode' => 'a', 'teks' => 'SOP penanganan pengaduan secara elektronik tersedia secara tertulis', 'urutan' => 1],
            ['ind_kode' => 'D9', 'kode' => 'b', 'teks' => 'Kanal pengaduan elektronik (form online/WA/aplikasi) tersedia dan berfungsi', 'urutan' => 2],
            ['ind_kode' => 'D9', 'kode' => 'c', 'teks' => 'Petugas menerapkan SOP tersebut secara konsisten saat menerima pengaduan', 'urutan' => 3],
            ['ind_kode' => 'D9', 'kode' => 'd', 'teks' => 'Setiap pengaduan elektronik tercatat dengan status yang dapat dipantau', 'urutan' => 4],
            ['ind_kode' => 'D9', 'kode' => 'e', 'teks' => 'SOP dievaluasi/diperbarui secara berkala berdasarkan pengalaman penanganan pengaduan', 'urutan' => 5],
            ['ind_kode' => 'D10', 'kode' => 'a', 'teks' => 'Sistem pengaduan digital mencatat waktu masuk setiap pengaduan', 'urutan' => 1],
            ['ind_kode' => 'D10', 'kode' => 'b', 'teks' => 'Respons awal terhadap pengaduan diberikan dalam paling lambat 1×24 jam kerja pada sampel yang diperiksa', 'urutan' => 2],
            ['ind_kode' => 'D10', 'kode' => 'c', 'teks' => 'Pengaduan yang masuk memiliki status penyelesaian yang jelas: selesai, proses, atau ditolak dengan alasan', 'urutan' => 3],
            ['ind_kode' => 'D10', 'kode' => 'd', 'teks' => 'Mayoritas pengaduan, lebih dari 70%, berstatus terselesaikan, bukan hanya tercatat', 'urutan' => 4],
            ['ind_kode' => 'D10', 'kode' => 'e', 'teks' => 'Tersedia laporan kinerja penanganan pengaduan, rata-rata waktu respons & tingkat resolusi, secara berkala', 'urutan' => 5],
            ['ind_kode' => 'F1a', 'kode' => 'a', 'teks' => 'Kecamatan/kelurahan memiliki data awal warga disabilitas & lansia berusia 60 tahun ke atas di wilayahnya', 'urutan' => 1],
            ['ind_kode' => 'F1a', 'kode' => 'b', 'teks' => 'Proses pendataan calon penerima yang belum terdaftar DTSEN telah dilakukan', 'urutan' => 2],
            ['ind_kode' => 'F1a', 'kode' => 'c', 'teks' => 'Musyawarah kelurahan diselenggarakan sebagai bagian dari proses pendataan tersebut', 'urutan' => 3],
            ['ind_kode' => 'F1a', 'kode' => 'd', 'teks' => 'Hasil pendataan mencakup seluruh kelurahan di kecamatan, tidak ada yang terlewat', 'urutan' => 4],
            ['ind_kode' => 'F1a', 'kode' => 'e', 'teks' => 'Tersedia dokumentasi (berita acara/daftar nama) hasil pendataan yang terarsip', 'urutan' => 5],
            ['ind_kode' => 'F1b', 'kode' => 'a', 'teks' => 'Aparatur memiliki akses ke sistem SIKS-NG', 'urutan' => 1],
            ['ind_kode' => 'F1b', 'kode' => 'b', 'teks' => 'Verifikasi status DTSEN dilakukan untuk calon penerima sebelum musyawarah kelurahan', 'urutan' => 2],
            ['ind_kode' => 'F1b', 'kode' => 'c', 'teks' => 'Verifikasi dilakukan secara real-time, langsung cek sistem, bukan berdasarkan data lama/cetakan usang', 'urutan' => 3],
            ['ind_kode' => 'F1b', 'kode' => 'd', 'teks' => 'Seluruh calon penerima yang diusulkan telah melalui proses verifikasi ini, tidak ada yang terlewat', 'urutan' => 4],
            ['ind_kode' => 'F1b', 'kode' => 'e', 'teks' => 'Tersedia bukti cetak/log hasil verifikasi SIKS-NG untuk tiap calon penerima', 'urutan' => 5],
            ['ind_kode' => 'F1c', 'kode' => 'a', 'teks' => 'Kecamatan memiliki data penerima PKH/BPNT/BSS tahun sebelumnya sebagai pembanding', 'urutan' => 1],
            ['ind_kode' => 'F1c', 'kode' => 'b', 'teks' => 'Proses pencocokan (cross-check) data calon penerima dengan data penerima tahun sebelumnya dilakukan', 'urutan' => 2],
            ['ind_kode' => 'F1c', 'kode' => 'c', 'teks' => 'Tidak ditemukan nama ganda/duplikasi pada sampel data yang diperiksa', 'urutan' => 3],
            ['ind_kode' => 'F1c', 'kode' => 'd', 'teks' => 'Bila ditemukan potensi duplikasi, terdapat proses klarifikasi/koreksi sebelum penetapan final', 'urutan' => 4],
            ['ind_kode' => 'F1c', 'kode' => 'e', 'teks' => 'Tersedia dokumentasi hasil cross-check yang menunjukkan proses ini dilakukan secara sistematis', 'urutan' => 5],
            ['ind_kode' => 'F2a', 'kode' => 'a', 'teks' => 'Berkas KK dan KTP tersedia untuk setiap calon penerima pada sampel yang diperiksa', 'urutan' => 1],
            ['ind_kode' => 'F2a', 'kode' => 'b', 'teks' => 'Foto seluruh badan dan foto rumah dengan geotag tersedia dalam berkas', 'urutan' => 2],
            ['ind_kode' => 'F2a', 'kode' => 'c', 'teks' => 'Surat domisili dari Lurah tersedia dalam berkas', 'urutan' => 3],
            ['ind_kode' => 'F2a', 'kode' => 'd', 'teks' => 'Surat pernyataan non-PKH/BPNT/BSS dan print-out DTSEN tersedia dalam berkas', 'urutan' => 4],
            ['ind_kode' => 'F2a', 'kode' => 'e', 'teks' => 'Seluruh dokumen di atas lengkap secara simultan untuk lebih dari 90% berkas pada sampel yang diperiksa', 'urutan' => 5],
            ['ind_kode' => 'F2b', 'kode' => 'a', 'teks' => 'Berita Acara Hasil Musyawarah Kelurahan tersedia secara tertulis untuk sampel yang diperiksa', 'urutan' => 1],
            ['ind_kode' => 'F2b', 'kode' => 'b', 'teks' => 'Berita Acara ditandatangani oleh unsur kelurahan (Lurah/Kasi Kesos)', 'urutan' => 2],
            ['ind_kode' => 'F2b', 'kode' => 'c', 'teks' => 'Berita Acara juga ditandatangani oleh unsur masyarakat yang dipersyaratkan (tokoh masyarakat/RT-RW)', 'urutan' => 3],
            ['ind_kode' => 'F2b', 'kode' => 'd', 'teks' => 'Seluruh unsur yang dipersyaratkan telah menandatangani, tidak ada tanda tangan yang kosong/diwakilkan tanpa dasar', 'urutan' => 4],
            ['ind_kode' => 'F2b', 'kode' => 'e', 'teks' => 'Berita Acara beserta berkas telah diserahkan dan tercatat diterima oleh Camat', 'urutan' => 5],
            ['ind_kode' => 'F2c', 'kode' => 'a', 'teks' => 'Surat pengajuan dari Camat tersedia secara tertulis', 'urutan' => 1],
            ['ind_kode' => 'F2c', 'kode' => 'b', 'teks' => 'Surat tersebut ditujukan sesuai prosedur, kepada Wali Kota c.q. Kepala Dinas Sosial', 'urutan' => 2],
            ['ind_kode' => 'F2c', 'kode' => 'c', 'teks' => 'Tanggal pengiriman surat sesuai dengan tenggat tahapan program yang ditetapkan', 'urutan' => 3],
            ['ind_kode' => 'F2c', 'kode' => 'd', 'teks' => 'Terdapat bukti tanda terima/pengiriman resmi (ekspedisi/tanda terima dinas)', 'urutan' => 4],
            ['ind_kode' => 'F2c', 'kode' => 'e', 'teks' => 'Tidak ditemukan keterlambatan pengajuan pada sampel periode yang diperiksa', 'urutan' => 5],
            ['ind_kode' => 'F3a', 'kode' => 'a', 'teks' => 'Musyawarah kelurahan benar-benar diselenggarakan, bukan hanya dokumen formalitas', 'urutan' => 1],
            ['ind_kode' => 'F3a', 'kode' => 'b', 'teks' => 'Daftar hadir musyawarah menunjukkan kehadiran unsur RT/RW', 'urutan' => 2],
            ['ind_kode' => 'F3a', 'kode' => 'c', 'teks' => 'Daftar hadir juga menunjukkan kehadiran tokoh masyarakat dan/atau PKK/Karang Taruna', 'urutan' => 3],
            ['ind_kode' => 'F3a', 'kode' => 'd', 'teks' => 'Seluruh unsur yang dipersyaratkan hadir secara bersamaan, bukan sebagian besar tidak hadir', 'urutan' => 4],
            ['ind_kode' => 'F3a', 'kode' => 'e', 'teks' => 'Notulen musyawarah mencatat substansi pembahasan penetapan penerima, bukan sekadar formalitas', 'urutan' => 5],
            ['ind_kode' => 'F3b', 'kode' => 'a', 'teks' => 'Daftar penerima yang ditetapkan dalam musyawarah tersedia secara tertulis', 'urutan' => 1],
            ['ind_kode' => 'F3b', 'kode' => 'b', 'teks' => 'Daftar tersebut diumumkan kepada warga melalui papan pengumuman/pertemuan warga', 'urutan' => 2],
            ['ind_kode' => 'F3b', 'kode' => 'c', 'teks' => 'Pengumuman dilakukan sebelum berkas diteruskan ke Camat, bukan setelah', 'urutan' => 3],
            ['ind_kode' => 'F3b', 'kode' => 'd', 'teks' => 'Warga memiliki kesempatan untuk melihat/mengetahui daftar tersebut secara terbuka', 'urutan' => 4],
            ['ind_kode' => 'F3b', 'kode' => 'e', 'teks' => 'Tersedia bukti pengumuman (foto/berita acara pengumuman) yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'F3c', 'kode' => 'a', 'teks' => 'Tersedia mekanisme/kanal bagi warga untuk mengajukan keberatan atas penetapan penerima', 'urutan' => 1],
            ['ind_kode' => 'F3c', 'kode' => 'b', 'teks' => 'Warga mengetahui keberadaan mekanisme tersebut, dikonfirmasi via wawancara', 'urutan' => 2],
            ['ind_kode' => 'F3c', 'kode' => 'c', 'teks' => 'Keberatan yang masuk dicatat secara resmi', 'urutan' => 3],
            ['ind_kode' => 'F3c', 'kode' => 'd', 'teks' => 'Setiap keberatan ditindaklanjuti dengan klarifikasi/keputusan yang disampaikan kembali ke pengadu', 'urutan' => 4],
            ['ind_kode' => 'F3c', 'kode' => 'e', 'teks' => 'Tersedia rekap keberatan & penyelesaiannya yang dapat ditelusuri', 'urutan' => 5],
            ['ind_kode' => 'F4a', 'kode' => 'a', 'teks' => 'Kecamatan/kelurahan memiliki jadwal kunjungan rutin untuk penerima disabilitas', 'urutan' => 1],
            ['ind_kode' => 'F4a', 'kode' => 'b', 'teks' => 'Kunjungan benar-benar dilaksanakan pada sampel penerima yang diperiksa dalam 3 bulan terakhir', 'urutan' => 2],
            ['ind_kode' => 'F4a', 'kode' => 'c', 'teks' => 'Petugas mencatat hasil kunjungan: kondisi penerima dan pemanfaatan bantuan', 'urutan' => 3],
            ['ind_kode' => 'F4a', 'kode' => 'd', 'teks' => 'Frekuensi kunjungan konsisten dengan jadwal yang ditetapkan, tidak hanya sekali di awal program', 'urutan' => 4],
            ['ind_kode' => 'F4a', 'kode' => 'e', 'teks' => 'Penerima yang diwawancarai mengonfirmasi pernah dikunjungi petugas', 'urutan' => 5],
            ['ind_kode' => 'F4b', 'kode' => 'a', 'teks' => 'Kecamatan/kelurahan memiliki jadwal kunjungan rutin untuk penerima lanjut usia', 'urutan' => 1],
            ['ind_kode' => 'F4b', 'kode' => 'b', 'teks' => 'Kunjungan benar-benar dilaksanakan pada sampel penerima yang diperiksa dalam 3 bulan terakhir', 'urutan' => 2],
            ['ind_kode' => 'F4b', 'kode' => 'c', 'teks' => 'Petugas mencatat kondisi kesehatan & kesejahteraan penerima pada setiap kunjungan', 'urutan' => 3],
            ['ind_kode' => 'F4b', 'kode' => 'd', 'teks' => 'Frekuensi kunjungan konsisten dengan jadwal yang ditetapkan', 'urutan' => 4],
            ['ind_kode' => 'F4b', 'kode' => 'e', 'teks' => 'Penerima yang diwawancarai mengonfirmasi pernah dikunjungi petugas', 'urutan' => 5],
            ['ind_kode' => 'F4c', 'kode' => 'a', 'teks' => 'Petugas pernah memberikan informasi tentang layanan sosial lain (kesehatan/adminduk) kepada penerima', 'urutan' => 1],
            ['ind_kode' => 'F4c', 'kode' => 'b', 'teks' => 'Petugas pernah membantu proses rujukan/pengurusan layanan sosial lain untuk penerima', 'urutan' => 2],
            ['ind_kode' => 'F4c', 'kode' => 'c', 'teks' => 'Penerima yang diwawancarai menyatakan mengetahui bantuan tersebut ditawarkan', 'urutan' => 3],
            ['ind_kode' => 'F4c', 'kode' => 'd', 'teks' => 'Penerima yang diwawancarai menyatakan benar-benar terbantu mengakses layanan lain', 'urutan' => 4],
            ['ind_kode' => 'F4c', 'kode' => 'e', 'teks' => 'Terdapat catatan/laporan kasus rujukan yang berhasil ditindaklanjuti hingga tuntas', 'urutan' => 5],
            ['ind_kode' => 'F4d', 'kode' => 'a', 'teks' => 'Kecamatan memiliki kontak/jalur koordinasi resmi dengan Dinas Sosial', 'urutan' => 1],
            ['ind_kode' => 'F4d', 'kode' => 'b', 'teks' => 'Kecamatan melaporkan perubahan status penerima, seperti meninggal, pindah, atau tidak layak, kepada Dinas Sosial', 'urutan' => 2],
            ['ind_kode' => 'F4d', 'kode' => 'c', 'teks' => 'Pelaporan dilakukan secara berkala, bukan hanya saat ditanya/diminta', 'urutan' => 3],
            ['ind_kode' => 'F4d', 'kode' => 'd', 'teks' => 'Terdapat bukti komunikasi/laporan tertulis dengan Dinas Sosial dalam 3 bulan terakhir', 'urutan' => 4],
            ['ind_kode' => 'F4d', 'kode' => 'e', 'teks' => 'Dinas Sosial mengonfirmasi menerima laporan tersebut secara rutin, jika dapat diverifikasi silang', 'urutan' => 5],
            ['ind_kode' => 'F5a', 'kode' => 'a', 'teks' => 'Aparatur yang ditugaskan memiliki akun aktif SIKS-NG', 'urutan' => 1],
            ['ind_kode' => 'F5a', 'kode' => 'b', 'teks' => 'Aparatur dapat login dan mengakses data tanpa bantuan pihak luar', 'urutan' => 2],
            ['ind_kode' => 'F5a', 'kode' => 'c', 'teks' => 'Aparatur dapat mendemonstrasikan pencarian status DTSEN calon penerima saat diminta', 'urutan' => 3],
            ['ind_kode' => 'F5a', 'kode' => 'd', 'teks' => 'Operasional SIKS-NG dilakukan sendiri secara rutin, bukan didelegasikan ke pihak ketiga/konsultan', 'urutan' => 4],
            ['ind_kode' => 'F5a', 'kode' => 'e', 'teks' => 'Aparatur pernah mengikuti pelatihan SIKS-NG dan memiliki bukti kompetensi (sertifikat/catatan pelatihan)', 'urutan' => 5],
            ['ind_kode' => 'F5b', 'kode' => 'a', 'teks' => 'Data usulan penerima dari kelurahan telah diinput ke dalam sistem digital', 'urutan' => 1],
            ['ind_kode' => 'F5b', 'kode' => 'b', 'teks' => 'Input data mencakup seluruh kelurahan di kecamatan, tidak ada yang tertinggal atau manual saja', 'urutan' => 2],
            ['ind_kode' => 'F5b', 'kode' => 'c', 'teks' => 'Data tersebut dapat diakses oleh Dinas Sosial melalui sistem tanpa kendala teknis', 'urutan' => 3],
            ['ind_kode' => 'F5b', 'kode' => 'd', 'teks' => 'Proses input dilakukan tepat waktu sesuai tahapan program, tidak menumpuk di akhir', 'urutan' => 4],
            ['ind_kode' => 'F5b', 'kode' => 'e', 'teks' => 'Tersedia bukti konfirmasi/tanda terima digital dari Dinas Sosial atas data yang diinput', 'urutan' => 5],
            ['ind_kode' => 'P1', 'kode' => 'a', 'teks' => 'Penerima pernah menerima penjelasan langsung dari petugas tentang program PKH Makmur', 'urutan' => 1],
            ['ind_kode' => 'P1', 'kode' => 'b', 'teks' => 'Penjelasan mencakup cara/prosedur untuk mendapatkan bantuan', 'urutan' => 2],
            ['ind_kode' => 'P1', 'kode' => 'c', 'teks' => 'Penjelasan mencakup syarat-syarat yang harus dipenuhi', 'urutan' => 3],
            ['ind_kode' => 'P1', 'kode' => 'd', 'teks' => 'Penerima menyatakan penjelasan tersebut mudah dipahami, bukan membingungkan', 'urutan' => 4],
            ['ind_kode' => 'P1', 'kode' => 'e', 'teks' => 'Penerima tidak perlu mencari informasi tambahan dari sumber lain karena penjelasan petugas sudah cukup jelas', 'urutan' => 5],
            ['ind_kode' => 'P2', 'kode' => 'a', 'teks' => 'Penerima mengetahui proses pendaftaran yang harus dilalui', 'urutan' => 1],
            ['ind_kode' => 'P2', 'kode' => 'b', 'teks' => 'Penerima tidak diminta dokumen/persyaratan di luar ketentuan yang berlaku', 'urutan' => 2],
            ['ind_kode' => 'P2', 'kode' => 'c', 'teks' => 'Proses verifikasi data berjalan tanpa meminta penerima bolak-balik berulang kali secara tidak wajar', 'urutan' => 3],
            ['ind_kode' => 'P2', 'kode' => 'd', 'teks' => 'Penerima tidak dikenakan biaya/pungutan apa pun dalam proses pendaftaran-verifikasi', 'urutan' => 4],
            ['ind_kode' => 'P2', 'kode' => 'e', 'teks' => 'Penerima menyatakan puas dengan kemudahan & transparansi keseluruhan proses', 'urutan' => 5],
            ['ind_kode' => 'P3', 'kode' => 'a', 'teks' => 'Penerima diperlakukan dengan sopan oleh petugas selama proses berlangsung', 'urutan' => 1],
            ['ind_kode' => 'P3', 'kode' => 'b', 'teks' => 'Penerima merasa didengar pendapatnya selama proses musyawarah', 'urutan' => 2],
            ['ind_kode' => 'P3', 'kode' => 'c', 'teks' => 'Penerima tidak merasa dibeda-bedakan dibanding calon penerima lain', 'urutan' => 3],
            ['ind_kode' => 'P3', 'kode' => 'd', 'teks' => 'Penerima tidak mengalami tekanan/intimidasi selama proses verifikasi', 'urutan' => 4],
            ['ind_kode' => 'P3', 'kode' => 'e', 'teks' => 'Penerima menyatakan secara keseluruhan diperlakukan adil dari awal hingga akhir proses', 'urutan' => 5],
            ['ind_kode' => 'P4', 'kode' => 'a', 'teks' => 'Penerima pernah dikunjungi atau dihubungi petugas setelah menerima bantuan', 'urutan' => 1],
            ['ind_kode' => 'P4', 'kode' => 'b', 'teks' => 'Kunjungan/kontak tersebut terjadi lebih dari satu kali, bukan hanya sekali di awal', 'urutan' => 2],
            ['ind_kode' => 'P4', 'kode' => 'c', 'teks' => 'Petugas menanyakan kondisi terkini penerima saat kunjungan/kontak', 'urutan' => 3],
            ['ind_kode' => 'P4', 'kode' => 'd', 'teks' => 'Petugas menanyakan/memantau bagaimana bantuan dimanfaatkan', 'urutan' => 4],
            ['ind_kode' => 'P4', 'kode' => 'e', 'teks' => 'Penerima menyatakan frekuensi kunjungan/kontak tersebut memadai sesuai kebutuhan mereka', 'urutan' => 5],
            ['ind_kode' => 'P5', 'kode' => 'a', 'teks' => 'Penerima menyatakan proses pendaftaran hingga penetapan berjalan baik', 'urutan' => 1],
            ['ind_kode' => 'P5', 'kode' => 'b', 'teks' => 'Penerima menyatakan bantuan yang diterima sesuai dengan yang dijanjikan', 'urutan' => 2],
            ['ind_kode' => 'P5', 'kode' => 'c', 'teks' => 'Penerima menyatakan pendampingan yang diterima bermanfaat', 'urutan' => 3],
            ['ind_kode' => 'P5', 'kode' => 'd', 'teks' => 'Penerima tidak memiliki keluhan besar yang belum terselesaikan terkait program ini', 'urutan' => 4],
            ['ind_kode' => 'P5', 'kode' => 'e', 'teks' => 'Penerima menyatakan akan merekomendasikan proses yang sama kepada tetangga/warga lain yang berhak', 'urutan' => 5],
            ['ind_kode' => 'G1a', 'kode' => 'a', 'teks' => 'Pejalan kaki terlihat menggunakan trotoar yang tersedia, bukan berjalan di badan jalan', 'urutan' => 1],
            ['ind_kode' => 'G1a', 'kode' => 'b', 'teks' => 'Warga menyeberang menggunakan zebra cross/tempat penyeberangan yang tersedia', 'urutan' => 2],
            ['ind_kode' => 'G1a', 'kode' => 'c', 'teks' => 'Tidak ditemukan pedagang berjualan di ruang milik jalan (Rumija) pada titik pantau', 'urutan' => 3],
            ['ind_kode' => 'G1a', 'kode' => 'd', 'teks' => 'Kondisi tertib jalan ini konsisten diamati di lebih dari satu titik/waktu pantau', 'urutan' => 4],
            ['ind_kode' => 'G1a', 'kode' => 'e', 'teks' => 'Kecamatan memiliki data/laporan pemantauan kepatuhan tertib jalan secara berkala', 'urutan' => 5],
            ['ind_kode' => 'G1b', 'kode' => 'a', 'teks' => 'Jalur hijau/taman yang dipantau tidak menunjukkan tanda kerusakan oleh aktivitas warga', 'urutan' => 1],
            ['ind_kode' => 'G1b', 'kode' => 'b', 'teks' => 'Tidak ditemukan sampah yang dibuang sembarangan di jalur hijau/taman', 'urutan' => 2],
            ['ind_kode' => 'G1b', 'kode' => 'c', 'teks' => 'Tidak ditemukan aktivitas berdagang di area jalur hijau/taman', 'urutan' => 3],
            ['ind_kode' => 'G1b', 'kode' => 'd', 'teks' => 'Kondisi ini konsisten pada lebih dari satu lokasi jalur hijau/taman yang dipantau', 'urutan' => 4],
            ['ind_kode' => 'G1b', 'kode' => 'e', 'teks' => 'Kecamatan memiliki laporan pemantauan/patroli jalur hijau yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'G1c', 'kode' => 'a', 'teks' => 'Tidak ditemukan pengemis yang mengganggu ketertiban di titik pantau saat kunjungan', 'urutan' => 1],
            ['ind_kode' => 'G1c', 'kode' => 'b', 'teks' => 'Tidak ditemukan anak jalanan yang meresahkan di titik pantau saat kunjungan', 'urutan' => 2],
            ['ind_kode' => 'G1c', 'kode' => 'c', 'teks' => 'Kecamatan memiliki data pemantauan terkait keberadaan pengemis/anak jalanan di wilayahnya', 'urutan' => 3],
            ['ind_kode' => 'G1c', 'kode' => 'd', 'teks' => 'Kondisi tertib ini konsisten pada lebih dari satu titik/waktu pemantauan', 'urutan' => 4],
            ['ind_kode' => 'G1c', 'kode' => 'e', 'teks' => 'Kecamatan memiliki laporan koordinasi penanganan isu ini dengan instansi terkait (Dinsos/Satpol PP)', 'urutan' => 5],
            ['ind_kode' => 'G1d', 'kode' => 'a', 'teks' => 'Selokan/saluran air di titik pantau terlihat relatif bersih dari sampah', 'urutan' => 1],
            ['ind_kode' => 'G1d', 'kode' => 'b', 'teks' => 'Tidak ditemukan tumpukan sampah baru di badan jalan pada titik pantau', 'urutan' => 2],
            ['ind_kode' => 'G1d', 'kode' => 'c', 'teks' => 'Terdapat indikasi kesadaran warga menjaga kebersihan, tidak ada praktik buang sampah yang teramati langsung', 'urutan' => 3],
            ['ind_kode' => 'G1d', 'kode' => 'd', 'teks' => 'Kondisi ini konsisten di lebih dari satu titik pemantauan dalam kecamatan', 'urutan' => 4],
            ['ind_kode' => 'G1d', 'kode' => 'e', 'teks' => 'Kecamatan memiliki program/laporan edukasi kebersihan lingkungan yang mendukung kondisi ini', 'urutan' => 5],
            ['ind_kode' => 'G2a', 'kode' => 'a', 'teks' => 'Zona prioritas penertiban PKL liar telah ditetapkan kecamatan', 'urutan' => 1],
            ['ind_kode' => 'G2a', 'kode' => 'b', 'teks' => 'Operasi penertiban PKL liar tercatat dilaksanakan minimal 1 kali pada bulan terakhir', 'urutan' => 2],
            ['ind_kode' => 'G2a', 'kode' => 'c', 'teks' => 'Frekuensi tersebut konsisten selama 3 bulan terakhir', 'urutan' => 3],
            ['ind_kode' => 'G2a', 'kode' => 'd', 'teks' => 'Operasi melibatkan koordinasi dengan Satpol PP wilayah, bukan hanya rencana kecamatan sendiri', 'urutan' => 4],
            ['ind_kode' => 'G2a', 'kode' => 'e', 'teks' => 'Tersedia laporan operasi penertiban (waktu, lokasi, hasil) yang terdokumentasi untuk setiap pelaksanaan', 'urutan' => 5],
            ['ind_kode' => 'G2b', 'kode' => 'a', 'teks' => 'Kecamatan/Satpol PP memiliki data bangunan liar/titik vandalisme yang teridentifikasi', 'urutan' => 1],
            ['ind_kode' => 'G2b', 'kode' => 'b', 'teks' => 'Tindakan penertiban/penindakan dilakukan terhadap temuan tersebut', 'urutan' => 2],
            ['ind_kode' => 'G2b', 'kode' => 'c', 'teks' => 'Terdapat bukti nyata hasil penindakan, seperti foto sebelum-sesudah atau relokasi/pembongkaran', 'urutan' => 3],
            ['ind_kode' => 'G2b', 'kode' => 'd', 'teks' => 'Lokasi yang telah ditertibkan tidak kembali muncul pelanggaran serupa dalam pemantauan berikutnya', 'urutan' => 4],
            ['ind_kode' => 'G2b', 'kode' => 'e', 'teks' => 'Tersedia laporan penertiban yang terdokumentasi lengkap dengan tindak lanjutnya', 'urutan' => 5],
            ['ind_kode' => 'G2c', 'kode' => 'a', 'teks' => 'Kecamatan memiliki jalur koordinasi resmi dengan Dinas Sosial dan Satpol PP terkait tertib sosial', 'urutan' => 1],
            ['ind_kode' => 'G2c', 'kode' => 'b', 'teks' => 'Kasus pelanggaran tertib sosial (pengemis, anak jalanan, miras ilegal) yang ditemukan dilaporkan ke instansi terkait', 'urutan' => 2],
            ['ind_kode' => 'G2c', 'kode' => 'c', 'teks' => 'Terdapat tindak lanjut nyata dari laporan tersebut, seperti razia bersama atau rujukan penanganan', 'urutan' => 3],
            ['ind_kode' => 'G2c', 'kode' => 'd', 'teks' => 'Koordinasi ini berjalan rutin, bukan hanya saat terjadi kasus besar/insidental', 'urutan' => 4],
            ['ind_kode' => 'G2c', 'kode' => 'e', 'teks' => 'Tersedia laporan/catatan koordinasi dan hasil penanganan yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'G2d', 'kode' => 'a', 'teks' => 'Tersedia kanal pengaduan ketertiban yang dapat diakses warga', 'urutan' => 1],
            ['ind_kode' => 'G2d', 'kode' => 'b', 'teks' => 'Pengaduan yang masuk dicatat dengan tanggal/waktu penerimaan', 'urutan' => 2],
            ['ind_kode' => 'G2d', 'kode' => 'c', 'teks' => 'Tindak lanjut atas pengaduan dilakukan dalam paling lambat 3 hari kerja pada sampel yang diperiksa', 'urutan' => 3],
            ['ind_kode' => 'G2d', 'kode' => 'd', 'teks' => 'Sebagian besar, lebih dari 70%, pengaduan pada sampel terselesaikan dalam tenggat tersebut', 'urutan' => 4],
            ['ind_kode' => 'G2d', 'kode' => 'e', 'teks' => 'Tersedia rekap pengaduan & waktu penyelesaian yang dapat diverifikasi', 'urutan' => 5],
            ['ind_kode' => 'G3a', 'kode' => 'a', 'teks' => 'Trotoar pada titik pantau dapat dilalui pejalan kaki tanpa hambatan berarti', 'urutan' => 1],
            ['ind_kode' => 'G3a', 'kode' => 'b', 'teks' => 'Tidak ditemukan PKL liar yang menghalangi jalan/trotoar di titik pantau', 'urutan' => 2],
            ['ind_kode' => 'G3a', 'kode' => 'c', 'teks' => 'Tidak ditemukan kendaraan parkir liar yang mengganggu arus jalan di titik pantau', 'urutan' => 3],
            ['ind_kode' => 'G3a', 'kode' => 'd', 'teks' => 'Tidak ditemukan material konstruksi yang dibiarkan menghalangi jalan/trotoar', 'urutan' => 4],
            ['ind_kode' => 'G3a', 'kode' => 'e', 'teks' => 'Kondisi bebas hambatan ini konsisten di lebih dari satu titik pemantauan', 'urutan' => 5],
            ['ind_kode' => 'G3b', 'kode' => 'a', 'teks' => 'Jalur hijau/taman/RTH pada titik pantau terlihat terawat, rumput/tanaman terpelihara', 'urutan' => 1],
            ['ind_kode' => 'G3b', 'kode' => 'b', 'teks' => 'Tidak ditemukan tanda vandalisme, seperti coretan atau kerusakan fasilitas, pada titik pantau', 'urutan' => 2],
            ['ind_kode' => 'G3b', 'kode' => 'c', 'teks' => 'Tidak ditemukan bangunan liar yang menempati area jalur hijau/RTH', 'urutan' => 3],
            ['ind_kode' => 'G3b', 'kode' => 'd', 'teks' => 'Fasilitas pendukung, seperti bangku, lampu taman, dan pagar, dalam kondisi berfungsi baik', 'urutan' => 4],
            ['ind_kode' => 'G3b', 'kode' => 'e', 'teks' => 'Kondisi terawat ini konsisten di lebih dari satu lokasi RTH yang dipantau', 'urutan' => 5],
            ['ind_kode' => 'G3c', 'kode' => 'a', 'teks' => 'Sungai/selokan pada titik pantau tidak dipenuhi sampah yang menyumbat aliran', 'urutan' => 1],
            ['ind_kode' => 'G3c', 'kode' => 'b', 'teks' => 'Tidak ditemukan aktivitas pembuangan sampah baru secara langsung ke sungai/selokan saat pemantauan', 'urutan' => 2],
            ['ind_kode' => 'G3c', 'kode' => 'c', 'teks' => 'Tidak ditemukan indikasi praktik buang air besar/kecil sembarangan di area tersebut', 'urutan' => 3],
            ['ind_kode' => 'G3c', 'kode' => 'd', 'teks' => 'Kondisi ini konsisten di lebih dari satu titik sungai/selokan yang dipantau', 'urutan' => 4],
            ['ind_kode' => 'G3c', 'kode' => 'e', 'teks' => 'Kecamatan memiliki program/laporan pemantauan kebersihan sungai & selokan secara berkala', 'urutan' => 5],
            ['ind_kode' => 'G4a', 'kode' => 'a', 'teks' => 'Kecamatan memiliki data usaha pariwisata/tempat usaha yang beroperasi di wilayahnya', 'urutan' => 1],
            ['ind_kode' => 'G4a', 'kode' => 'b', 'teks' => 'Sampel usaha yang diperiksa memiliki izin resmi yang berlaku', 'urutan' => 2],
            ['ind_kode' => 'G4a', 'kode' => 'c', 'teks' => 'Tidak ditemukan usaha yang beroperasi tanpa izin pada sampel yang diperiksa', 'urutan' => 3],
            ['ind_kode' => 'G4a', 'kode' => 'd', 'teks' => 'Tidak ada laporan/keluhan gangguan ketertiban umum akibat aktivitas usaha tersebut', 'urutan' => 4],
            ['ind_kode' => 'G4a', 'kode' => 'e', 'teks' => 'Kecamatan memiliki mekanisme pengawasan izin usaha yang berjalan rutin', 'urutan' => 5],
            ['ind_kode' => 'G4b', 'kode' => 'a', 'teks' => 'Tidak ditemukan reklame/baliho tanpa izin pada titik pantau', 'urutan' => 1],
            ['ind_kode' => 'G4b', 'kode' => 'b', 'teks' => 'Tidak ditemukan portal jalan yang dipasang tanpa izin resmi', 'urutan' => 2],
            ['ind_kode' => 'G4b', 'kode' => 'c', 'teks' => 'Tidak ditemukan aktivitas terminal bayangan atau angkutan liar pada titik pantau', 'urutan' => 3],
            ['ind_kode' => 'G4b', 'kode' => 'd', 'teks' => 'Kondisi bebas pelanggaran ini konsisten di lebih dari satu titik pemantauan', 'urutan' => 4],
            ['ind_kode' => 'G4b', 'kode' => 'e', 'teks' => 'Kecamatan memiliki laporan penertiban reklame/portal/terminal liar bila sebelumnya ditemukan pelanggaran', 'urutan' => 5],
            ['ind_kode' => 'G5a', 'kode' => 'a', 'teks' => 'Struktur/jadwal siskamling atau ronda malam tercatat di tingkat RT/RW', 'urutan' => 1],
            ['ind_kode' => 'G5a', 'kode' => 'b', 'teks' => 'Pos ronda/siskamling secara fisik tersedia dan terawat', 'urutan' => 2],
            ['ind_kode' => 'G5a', 'kode' => 'c', 'teks' => 'Pelaksanaan ronda malam terkonfirmasi berjalan pada sampel RT/RW yang diperiksa', 'urutan' => 3],
            ['ind_kode' => 'G5a', 'kode' => 'd', 'teks' => 'Pelaksanaan tersebut konsisten, bukan hanya formalitas jadwal tanpa realisasi', 'urutan' => 4],
            ['ind_kode' => 'G5a', 'kode' => 'e', 'teks' => 'Tersedia catatan/laporan kegiatan siskamling yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'G5b', 'kode' => 'a', 'teks' => 'Warga mengetahui adanya saluran pelaporan pelanggaran ketertiban', 'urutan' => 1],
            ['ind_kode' => 'G5b', 'kode' => 'b', 'teks' => 'Terdapat catatan laporan dari warga yang masuk melalui saluran tersebut', 'urutan' => 2],
            ['ind_kode' => 'G5b', 'kode' => 'c', 'teks' => 'Jumlah laporan warga menunjukkan partisipasi aktif, bukan nol laporan dalam periode panjang tanpa penjelasan', 'urutan' => 3],
            ['ind_kode' => 'G5b', 'kode' => 'd', 'teks' => 'Warga yang pernah melapor menyatakan mengetahui saluran tersebut dengan mudah', 'urutan' => 4],
            ['ind_kode' => 'G5b', 'kode' => 'e', 'teks' => 'Kecamatan memiliki rekap laporan warga & tindak lanjutnya yang terdokumentasi', 'urutan' => 5],
            ['ind_kode' => 'G5c', 'kode' => 'a', 'teks' => 'Kecamatan memiliki rencana sosialisasi Perda Ketertiban', 'urutan' => 1],
            ['ind_kode' => 'G5c', 'kode' => 'b', 'teks' => 'Sosialisasi benar-benar dilaksanakan minimal 1 kali dalam semester terakhir', 'urutan' => 2],
            ['ind_kode' => 'G5c', 'kode' => 'c', 'teks' => 'Materi sosialisasi mencakup substansi Perda No.10/2021 secara memadai', 'urutan' => 3],
            ['ind_kode' => 'G5c', 'kode' => 'd', 'teks' => 'Sosialisasi menjangkau lebih dari satu kelurahan/RT dalam kecamatan', 'urutan' => 4],
            ['ind_kode' => 'G5c', 'kode' => 'e', 'teks' => 'Tersedia dokumentasi (daftar hadir/foto/laporan) pelaksanaan sosialisasi tersebut', 'urutan' => 5],
            ['ind_kode' => 'W1', 'kode' => 'a', 'teks' => 'Warga dapat menggunakan trotoar/jalan tanpa hambatan berarti dalam kesehariannya', 'urutan' => 1],
            ['ind_kode' => 'W1', 'kode' => 'b', 'teks' => 'Warga tidak mengalami gangguan berulang akibat PKL liar/parkir liar di lingkungannya', 'urutan' => 2],
            ['ind_kode' => 'W1', 'kode' => 'c', 'teks' => 'Fasilitas umum di lingkungan warga dalam kondisi terawat menurut pengamatan warga', 'urutan' => 3],
            ['ind_kode' => 'W1', 'kode' => 'd', 'teks' => 'Warga menilai kondisi ini stabil/tidak memburuk dalam 6 bulan terakhir', 'urutan' => 4],
            ['ind_kode' => 'W1', 'kode' => 'e', 'teks' => 'Warga menyatakan puas secara keseluruhan terhadap ketertiban jalan & fasilitas umum di lingkungannya', 'urutan' => 5],
            ['ind_kode' => 'W2', 'kode' => 'a', 'teks' => 'Warga pernah melihat kehadiran/patroli Satpol PP di wilayahnya', 'urutan' => 1],
            ['ind_kode' => 'W2', 'kode' => 'b', 'teks' => 'Warga mengetahui adanya operasi penertiban yang dilakukan Satpol PP', 'urutan' => 2],
            ['ind_kode' => 'W2', 'kode' => 'c', 'teks' => 'Warga menilai operasi tersebut membawa perubahan/perbaikan nyata di lingkungannya', 'urutan' => 3],
            ['ind_kode' => 'W2', 'kode' => 'd', 'teks' => 'Warga tidak mengalami pelanggaran ketertiban yang berulang meski sudah dilaporkan', 'urutan' => 4],
            ['ind_kode' => 'W2', 'kode' => 'e', 'teks' => 'Warga menyatakan puas secara keseluruhan dengan efektivitas kinerja Satpol PP', 'urutan' => 5],
            ['ind_kode' => 'W3', 'kode' => 'a', 'teks' => 'Warga menilai jalur hijau/taman di lingkungannya dalam kondisi bersih', 'urutan' => 1],
            ['ind_kode' => 'W3', 'kode' => 'b', 'teks' => 'Warga tidak menemukan tanda vandalisme yang dibiarkan dalam waktu lama', 'urutan' => 2],
            ['ind_kode' => 'W3', 'kode' => 'c', 'teks' => 'Warga menilai sungai/selokan di lingkungannya relatif bebas sampah', 'urutan' => 3],
            ['ind_kode' => 'W3', 'kode' => 'd', 'teks' => 'Warga menilai kondisi ini stabil/membaik dalam 6 bulan terakhir', 'urutan' => 4],
            ['ind_kode' => 'W3', 'kode' => 'e', 'teks' => 'Warga menyatakan puas secara keseluruhan dengan kondisi ruang hijau & saluran air di lingkungannya', 'urutan' => 5],
            ['ind_kode' => 'W4', 'kode' => 'a', 'teks' => 'Warga tidak mengalami/menyaksikan tindak kejahatan di lingkungannya dalam 6 bulan terakhir', 'urutan' => 1],
            ['ind_kode' => 'W4', 'kode' => 'b', 'teks' => 'Warga tidak mengalami gangguan premanisme di lingkungannya', 'urutan' => 2],
            ['ind_kode' => 'W4', 'kode' => 'c', 'teks' => 'Warga merasa aman beraktivitas di lingkungannya pada siang maupun malam hari', 'urutan' => 3],
            ['ind_kode' => 'W4', 'kode' => 'd', 'teks' => 'Warga menilai kondisi keamanan ini stabil/membaik dibanding periode sebelumnya', 'urutan' => 4],
            ['ind_kode' => 'W4', 'kode' => 'e', 'teks' => 'Warga menyatakan puas secara keseluruhan terhadap rasa aman & tenteram di lingkungannya', 'urutan' => 5],
            ['ind_kode' => 'W5', 'kode' => 'a', 'teks' => 'Warga menilai kondisi ketertiban umum secara umum membaik atau setidaknya tidak memburuk', 'urutan' => 1],
            ['ind_kode' => 'W5', 'kode' => 'b', 'teks' => 'Warga tidak memiliki keluhan besar yang belum tertangani terkait ketertiban di wilayahnya', 'urutan' => 2],
            ['ind_kode' => 'W5', 'kode' => 'c', 'teks' => 'Warga merasa aparat, kecamatan & Satpol PP, responsif terhadap isu ketertiban', 'urutan' => 3],
            ['ind_kode' => 'W5', 'kode' => 'd', 'teks' => 'Warga merasa dilibatkan/didengar dalam upaya menjaga ketertiban wilayahnya', 'urutan' => 4],
            ['ind_kode' => 'W5', 'kode' => 'e', 'teks' => 'Warga menyatakan puas secara keseluruhan dengan tingkat ketertiban umum di kecamatan ini', 'urutan' => 5],
        ];

        foreach ($data as $row) {
            if (isset($indikators[$row['ind_kode']])) {
                $subItems[] = [
                    'indikator_id' => $indikators[$row['ind_kode']],
                    'kode' => $row['kode'],
                    'teks' => $row['teks'],
                    'urutan' => $row['urutan'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }
        }

        Schema::disableForeignKeyConstraints();
        SubItem::truncate();
        Schema::enableForeignKeyConstraints();
        foreach (array_chunk($subItems, 100) as $chunk) {
            SubItem::insert($chunk);
        }
    }
}
